/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by generate.go. DO NOT EDIT.

// +kubebuilder:object:generate=true

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	xpv1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

// ApplicationSettingsParameters defines the desired state for ApplicationSettings
// This struct was generated from gitlab.UpdateSettingsOptions struct, with just a rework of the json tags.
type ApplicationSettingsParameters struct {
	// +optional
	AbuseNotificationEmail *string `json:"abuseNotificationEmail,omitempty"`
	// +optional
	AdminMode *bool `json:"adminMode,omitempty"`
	// +optional
	AfterSignOutPath *string `json:"afterSignOutPath,omitempty"`
	// +optional
	AfterSignUpText *string `json:"afterSignUpText,omitempty"`
	// +optional
	AkismetAPIKey *string `json:"akismetApiKey,omitempty"`
	// +optional
	AkismetAPIKeySecretRef *xpv1.LocalSecretKeySelector `json:"akismetApiKeySecretRef,omitempty"`
	// +optional
	AkismetEnabled *bool `json:"akismetEnabled,omitempty"`
	// +optional
	AllowAccountDeletion *bool `json:"allowAccountDeletion,omitempty"`
	// +optional
	AllowAllIntegrations *bool `json:"allowAllIntegrations,omitempty"`
	// +optional
	AllowedIntegrations *[]string `json:"allowedIntegrations,omitempty"`
	// +optional
	AllowGroupOwnersToManageLDAP *bool `json:"allowGroupOwnersToManageLdap,omitempty"`
	// +optional
	AllowLocalRequestsFromSystemHooks *bool `json:"allowLocalRequestsFromSystemHooks,omitempty"`
	// +optional
	AllowLocalRequestsFromWebHooksAndServices *bool `json:"allowLocalRequestsFromWebHooksAndServices,omitempty"`
	// +optional
	AllowProjectCreationForGuestAndBelow *bool `json:"allowProjectCreationForGuestAndBelow,omitempty"`
	// +optional
	AllowRunnerRegistrationToken *bool `json:"allowRunnerRegistrationToken,omitempty"`
	// +optional
	ArchiveBuildsInHumanReadable *string `json:"archiveBuildsInHumanReadable,omitempty"`
	// +optional
	ASCIIDocMaxIncludes *int64 `json:"asciiDocMaxIncludes,omitempty"`
	// +optional
	AssetProxyAllowlist *[]string `json:"assetProxyAllowlist,omitempty"`
	// +optional
	AssetProxyEnabled *bool `json:"assetProxyEnabled,omitempty"`
	// +optional
	AssetProxySecretKey *string `json:"assetProxySecretKey,omitempty"`
	// +optional
	AssetProxySecretKeySecretRef *xpv1.LocalSecretKeySelector `json:"assetProxySecretKeySecretRef,omitempty"`
	// +optional
	AssetProxyURL *string `json:"assetProxyUrl,omitempty"`
	// +optional
	AuthorizedKeysEnabled *bool `json:"authorizedKeysEnabled,omitempty"`
	// +optional
	AutoBanUserOnExcessiveProjectsDownload *bool `json:"autoBanUserOnExcessiveProjectsDownload,omitempty"`
	// +optional
	AutocompleteUsers *int64 `json:"autocompleteUsers,omitempty"`
	// +optional
	AutocompleteUsersUnauthenticated *int64 `json:"autocompleteUsersUnauthenticated,omitempty"`
	// +optional
	AutoDevOpsDomain *string `json:"autoDevOpsDomain,omitempty"`
	// +optional
	AutoDevOpsEnabled *bool `json:"autoDevOpsEnabled,omitempty"`
	// +optional
	AutomaticPurchasedStorageAllocation *bool `json:"automaticPurchasedStorageAllocation,omitempty"`
	// +optional
	BulkImportConcurrentPipelineBatchLimit *int64 `json:"bulkImportConcurrentPipelineBatchLimit,omitempty"`
	// +optional
	BulkImportEnabled *bool `json:"bulkImportEnabled,omitempty"`
	// +optional
	BulkImportMaxDownloadFileSize *int64 `json:"bulkImportMaxDownloadFileSize,omitempty"`
	// +optional
	CanCreateGroup *bool `json:"canCreateGroup,omitempty"`
	// +optional
	CanCreateOrganization *bool `json:"canCreateOrganization,omitempty"`
	// +optional
	CheckNamespacePlan *bool `json:"checkNamespacePlan,omitempty"`
	// +optional
	CIJobLiveTraceEnabled *bool `json:"ciJobLiveTraceEnabled,omitempty"`
	// +optional
	CIMaxIncludes *int64 `json:"ciMaxIncludes,omitempty"`
	// +optional
	CIMaxTotalYAMLSizeBytes *int64 `json:"ciMaxTotalYamlSizeBytes,omitempty"`
	// +optional
	CIPartitionsSizeLimit *int64 `json:"ciPartitionsSizeLimit,omitempty"`
	// +optional
	CommitEmailHostname *string `json:"commitEmailHostname,omitempty"`
	// +optional
	ConcurrentBitbucketImportJobsLimit *int64 `json:"concurrentBitbucketImportJobsLimit,omitempty"`
	// +optional
	ConcurrentBitbucketServerImportJobsLimit *int64 `json:"concurrentBitbucketServerImportJobsLimit,omitempty"`
	// +optional
	ConcurrentGitHubImportJobsLimit *int64 `json:"concurrentGitHubImportJobsLimit,omitempty"`
	// +optional
	ContainerExpirationPoliciesEnableHistoricEntries *bool `json:"containerExpirationPoliciesEnableHistoricEntries,omitempty"`
	// +optional
	ContainerRegistryCleanupTagsServiceMaxListSize *int64 `json:"containerRegistryCleanupTagsServiceMaxListSize,omitempty"`
	// +optional
	ContainerRegistryDeleteTagsServiceTimeout *int64 `json:"containerRegistryDeleteTagsServiceTimeout,omitempty"`
	// +optional
	ContainerRegistryExpirationPoliciesCaching *bool `json:"containerRegistryExpirationPoliciesCaching,omitempty"`
	// +optional
	ContainerRegistryExpirationPoliciesWorkerCapacity *int64 `json:"containerRegistryExpirationPoliciesWorkerCapacity,omitempty"`
	// +optional
	ContainerRegistryImportCreatedBefore *metav1.Time `json:"containerRegistryImportCreatedBefore,omitempty"`
	// +optional
	ContainerRegistryImportMaxRetries *int64 `json:"containerRegistryImportMaxRetries,omitempty"`
	// +optional
	ContainerRegistryImportMaxStepDuration *int64 `json:"containerRegistryImportMaxStepDuration,omitempty"`
	// +optional
	ContainerRegistryImportMaxTagsCount *int64 `json:"containerRegistryImportMaxTagsCount,omitempty"`
	// +optional
	ContainerRegistryImportStartMaxRetries *int64 `json:"containerRegistryImportStartMaxRetries,omitempty"`
	// +optional
	ContainerRegistryImportTargetPlan *string `json:"containerRegistryImportTargetPlan,omitempty"`
	// +optional
	ContainerRegistryTokenExpireDelay *int64 `json:"containerRegistryTokenExpireDelay,omitempty"`
	// +optional
	CustomHTTPCloneURLRoot *string `json:"customHTTPCloneUrlRoot,omitempty"`
	// +optional
	DNSRebindingProtectionEnabled *bool `json:"dnsRebindingProtectionEnabled,omitempty"`
	// +optional
	DSAKeyRestriction *int64 `json:"dsaKeyRestriction,omitempty"`
	// +optional
	DeactivateDormantUsers *bool `json:"deactivateDormantUsers,omitempty"`
	// +optional
	DeactivateDormantUsersPeriod *int64 `json:"deactivateDormantUsersPeriod,omitempty"`
	// +optional
	DecompressArchiveFileTimeout *int64 `json:"decompressArchiveFileTimeout,omitempty"`
	// +optional
	DefaultArtifactsExpireIn *string `json:"defaultArtifactsExpireIn,omitempty"`
	// +optional
	DefaultBranchName *string `json:"defaultBranchName,omitempty"`
	// +optional
	DefaultBranchProtectionDefaults *DefaultBranchProtectionDefaultsOptions `json:"defaultBranchProtectionDefaults,omitempty"`
	// +optional
	DefaultCiConfigPath *string `json:"defaultCiConfigPath,omitempty"`
	// +optional
	DefaultGroupVisibility *string `json:"defaultGroupVisibility,omitempty"`
	// +optional
	DefaultPreferredLanguage *string `json:"defaultPreferredLanguage,omitempty"`
	// +optional
	DefaultProjectCreation *int64 `json:"defaultProjectCreation,omitempty"`
	// +optional
	DefaultProjectDeletionProtection *bool `json:"defaultProjectDeletionProtection,omitempty"`
	// +optional
	DefaultProjectVisibility *string `json:"defaultProjectVisibility,omitempty"`
	// +optional
	DefaultProjectsLimit *int64 `json:"defaultProjectsLimit,omitempty"`
	// +optional
	DefaultSnippetVisibility *string `json:"defaultSnippetVisibility,omitempty"`
	// +optional
	DefaultSyntaxHighlightingTheme *int64 `json:"defaultSyntaxHighlightingTheme,omitempty"`
	// +optional
	DelayedGroupDeletion *bool `json:"delayedGroupDeletion,omitempty"`
	// +optional
	DelayedProjectDeletion *bool `json:"delayedProjectDeletion,omitempty"`
	// +optional
	DeleteInactiveProjects *bool `json:"deleteInactiveProjects,omitempty"`
	// +optional
	DeleteUnconfirmedUsers *bool `json:"deleteUnconfirmedUsers,omitempty"`
	// +optional
	DeletionAdjournedPeriod *int64 `json:"deletionAdjournedPeriod,omitempty"`
	// +optional
	DiagramsnetEnabled *bool `json:"diagramsnetEnabled,omitempty"`
	// +optional
	DiagramsnetURL *string `json:"diagramsnetUrl,omitempty"`
	// +optional
	DiffMaxFiles *int64 `json:"diffMaxFiles,omitempty"`
	// +optional
	DiffMaxLines *int64 `json:"diffMaxLines,omitempty"`
	// +optional
	DiffMaxPatchBytes *int64 `json:"diffMaxPatchBytes,omitempty"`
	// +optional
	DisableFeedToken *bool `json:"disableFeedToken,omitempty"`
	// +optional
	DisableAdminOAuthScopes *bool `json:"disableAdminOAuthScopes,omitempty"`
	// +optional
	DisableOverridingApproversPerMergeRequest *bool `json:"disableOverridingApproversPerMergeRequest,omitempty"`
	// +optional
	DisablePersonalAccessTokens *bool `json:"disablePersonalAccessTokens,omitempty"`
	// +optional
	DisabledOauthSignInSources *[]string `json:"disabledOauthSignInSources,omitempty"`
	// +optional
	DomainAllowlist *[]string `json:"domainAllowlist,omitempty"`
	// +optional
	DomainDenylist *[]string `json:"domainDenylist,omitempty"`
	// +optional
	DomainDenylistEnabled *bool `json:"domainDenylistEnabled,omitempty"`
	// +optional
	DownstreamPipelineTriggerLimitPerProjectUserSHA *int64 `json:"downstreamPipelineTriggerLimitPerProjectUserSHA,omitempty"`
	// +optional
	DuoFeaturesEnabled *bool `json:"duoFeaturesEnabled,omitempty"`
	// +optional
	ECDSAKeyRestriction *int64 `json:"ecdsaKeyRestriction,omitempty"`
	// +optional
	ECDSASKKeyRestriction *int64 `json:"ecdsaskKeyRestriction,omitempty"`
	// +optional
	EKSAccessKeyID *string `json:"eksAccessKeyId,omitempty"`
	// +optional
	EKSAccessKeyIDSecretRef *xpv1.LocalSecretKeySelector `json:"eksAccessKeyIdSecretRef,omitempty"`
	// +optional
	EKSAccountID *string `json:"eksAccountId,omitempty"`
	// +optional
	EKSIntegrationEnabled *bool `json:"eksIntegrationEnabled,omitempty"`
	// +optional
	EKSSecretAccessKey *string `json:"eksSecretAccessKey,omitempty"`
	// +optional
	EKSSecretAccessKeySecretRef *xpv1.LocalSecretKeySelector `json:"eksSecretAccessKeySecretRef,omitempty"`
	// +optional
	Ed25519KeyRestriction *int64 `json:"ed25519KeyRestriction,omitempty"`
	// +optional
	Ed25519SKKeyRestriction *int64 `json:"ed25519SKKeyRestriction,omitempty"`
	// +optional
	ElasticsearchAWS *bool `json:"elasticsearchAws,omitempty"`
	// +optional
	ElasticsearchAWSAccessKey *string `json:"elasticsearchAwsAccessKey,omitempty"`
	// +optional
	ElasticsearchAWSAccessKeySecretRef *xpv1.LocalSecretKeySelector `json:"elasticsearchAwsAccessKeySecretRef,omitempty"`
	// +optional
	ElasticsearchAWSRegion *string `json:"elasticsearchAwsRegion,omitempty"`
	// +optional
	ElasticsearchAWSSecretAccessKey *string `json:"elasticsearchAwsSecretAccessKey,omitempty"`
	// +optional
	ElasticsearchAWSSecretAccessKeySecretRef *xpv1.LocalSecretKeySelector `json:"elasticsearchAwsSecretAccessKeySecretRef,omitempty"`
	// +optional
	ElasticsearchAnalyzersKuromojiEnabled *bool `json:"elasticsearchAnalyzersKuromojiEnabled,omitempty"`
	// +optional
	ElasticsearchAnalyzersKuromojiSearch *int64 `json:"elasticsearchAnalyzersKuromojiSearch,omitempty"`
	// +optional
	ElasticsearchAnalyzersSmartCNEnabled *bool `json:"elasticsearchAnalyzersSmartCnEnabled,omitempty"`
	// +optional
	ElasticsearchAnalyzersSmartCNSearch *int64 `json:"elasticsearchAnalyzersSmartCnSearch,omitempty"`
	// +optional
	ElasticsearchClientRequestTimeout *int64 `json:"elasticsearchClientRequestTimeout,omitempty"`
	// +optional
	ElasticsearchIndexedFieldLengthLimit *int64 `json:"elasticsearchIndexedFieldLengthLimit,omitempty"`
	// +optional
	ElasticsearchIndexedFileSizeLimitKB *int64 `json:"elasticsearchIndexedFileSizeLimitKB,omitempty"`
	// +optional
	ElasticsearchIndexing *bool `json:"elasticsearchIndexing,omitempty"`
	// +optional
	ElasticsearchLimitIndexing *bool `json:"elasticsearchLimitIndexing,omitempty"`
	// +optional
	ElasticsearchMaxBulkConcurrency *int64 `json:"elasticsearchMaxBulkConcurrency,omitempty"`
	// +optional
	ElasticsearchMaxBulkSizeMB *int64 `json:"elasticsearchMaxBulkSizeMB,omitempty"`
	// +optional
	ElasticsearchMaxCodeIndexingConcurrency *int64 `json:"elasticsearchMaxCodeIndexingConcurrency,omitempty"`
	// +optional
	ElasticsearchNamespaceIDs *[]int64 `json:"elasticsearchNamespaceIds,omitempty"`
	// +optional
	ElasticsearchPassword *string `json:"elasticsearchPassword,omitempty"`
	// +optional
	ElasticsearchPasswordSecretRef *xpv1.LocalSecretKeySelector `json:"elasticsearchPasswordSecretRef,omitempty"`
	// +optional
	ElasticsearchPauseIndexing *bool `json:"elasticsearchPauseIndexing,omitempty"`
	// +optional
	ElasticsearchProjectIDs *[]int64 `json:"elasticsearchProjectIds,omitempty"`
	// +optional
	ElasticsearchReplicas *int64 `json:"elasticsearchReplicas,omitempty"`
	// +optional
	ElasticsearchRequeueWorkers *bool `json:"elasticsearchRequeueWorkers,omitempty"`
	// +optional
	ElasticsearchRetryOnFailure *int64 `json:"elasticsearchRetryOnFailure,omitempty"`
	// +optional
	ElasticsearchSearch *bool `json:"elasticsearchSearch,omitempty"`
	// +optional
	ElasticsearchShards *int64 `json:"elasticsearchShards,omitempty"`
	// +optional
	ElasticsearchURL *string `json:"elasticsearchUrl,omitempty"`
	// +optional
	ElasticsearchUsername *string `json:"elasticsearchUsername,omitempty"`
	// +optional
	ElasticsearchWorkerNumberOfShards *int64 `json:"elasticsearchWorkerNumberOfShards,omitempty"`
	// +optional
	EmailAdditionalText *string `json:"emailAdditionalText,omitempty"`
	// +optional
	EmailAuthorInBody *bool `json:"emailAuthorInBody,omitempty"`
	// +optional
	EmailConfirmationSetting *string `json:"emailConfirmationSetting,omitempty"`
	// +optional
	EmailRestrictions *string `json:"emailRestrictions,omitempty"`
	// +optional
	EmailRestrictionsEnabled *bool `json:"emailRestrictionsEnabled,omitempty"`
	// +optional
	EnableArtifactExternalRedirectWarningPage *bool `json:"enableArtifactExternalRedirectWarningPage,omitempty"`
	// +optional
	EnabledGitAccessProtocol *string `json:"enabledGitAccessProtocol,omitempty"`
	// +optional
	EnforceCIInboundJobTokenScopeEnabled *bool `json:"enforceCIInboundJobTokenScopeEnabled,omitempty"`
	// +optional
	EnforceNamespaceStorageLimit *bool `json:"enforceNamespaceStorageLimit,omitempty"`
	// +optional
	EnforcePATExpiration *bool `json:"enforcePATExpiration,omitempty"`
	// +optional
	EnforceSSHKeyExpiration *bool `json:"enforceSshKeyExpiration,omitempty"`
	// +optional
	EnforceTerms *bool `json:"enforceTerms,omitempty"`
	// +optional
	ExternalAuthClientCert *string `json:"externalAuthClientCert,omitempty"`
	// +optional
	ExternalAuthClientKey *string `json:"externalAuthClientKey,omitempty"`
	// +optional
	ExternalAuthClientKeySecretRef *xpv1.LocalSecretKeySelector `json:"externalAuthClientKeySecretRef,omitempty"`
	// +optional
	ExternalAuthClientKeyPass *string `json:"externalAuthClientKeyPass,omitempty"`
	// +optional
	ExternalAuthorizationServiceDefaultLabel *string `json:"externalAuthorizationServiceDefaultLabel,omitempty"`
	// +optional
	ExternalAuthorizationServiceEnabled *bool `json:"externalAuthorizationServiceEnabled,omitempty"`
	// +optional
	ExternalAuthorizationServiceTimeout *float64 `json:"externalAuthorizationServiceTimeout,omitempty"`
	// +optional
	ExternalAuthorizationServiceURL *string `json:"externalAuthorizationServiceUrl,omitempty"`
	// +optional
	ExternalPipelineValidationServiceTimeout *int64 `json:"externalPipelineValidationServiceTimeout,omitempty"`
	// +optional
	ExternalPipelineValidationServiceToken *string `json:"externalPipelineValidationServiceToken,omitempty"`
	// +optional
	ExternalPipelineValidationServiceTokenSecretRef *xpv1.LocalSecretKeySelector `json:"externalPipelineValidationServiceTokenSecretRef,omitempty"`
	// +optional
	ExternalPipelineValidationServiceURL *string `json:"externalPipelineValidationServiceUrl,omitempty"`
	// +optional
	FailedLoginAttemptsUnlockPeriodInMinutes *int64 `json:"failedLoginAttemptsUnlockPeriodInMinutes,omitempty"`
	// +optional
	FileTemplateProjectID *int64 `json:"fileTemplateProjectId,omitempty"`
	// +optional
	FirstDayOfWeek *int64 `json:"firstDayOfWeek,omitempty"`
	// +optional
	FlocEnabled *bool `json:"flocEnabled,omitempty"`
	// +optional
	GeoNodeAllowedIPs *string `json:"geoNodeAllowedIps,omitempty"`
	// +optional
	GeoStatusTimeout *int64 `json:"geoStatusTimeout,omitempty"`
	// +optional
	GitRateLimitUsersAlertlist *[]int64 `json:"gitRateLimitUsersAlertlist,omitempty"`
	// +optional
	GitTwoFactorSessionExpiry *int64 `json:"gitTwoFactorSessionExpiry,omitempty"`
	// +optional
	GitalyTimeoutDefault *int64 `json:"gitalyTimeoutDefault,omitempty"`
	// +optional
	GitalyTimeoutFast *int64 `json:"gitalyTimeoutFast,omitempty"`
	// +optional
	GitalyTimeoutMedium *int64 `json:"gitalyTimeoutMedium,omitempty"`
	// +optional
	GitlabDedicatedInstance *bool `json:"gitlabDedicatedInstance,omitempty"`
	// +optional
	GitlabEnvironmentToolkitInstance *bool `json:"gitlabEnvironmentToolkitInstance,omitempty"`
	// +optional
	GitlabShellOperationLimit *int64 `json:"gitlabShellOperationLimit,omitempty"`
	// +optional
	GitpodEnabled *bool `json:"gitpodEnabled,omitempty"`
	// +optional
	GitpodURL *string `json:"gitpodUrl,omitempty"`
	// +optional
	GitRateLimitUsersAllowlist *[]string `json:"gitRateLimitUsersAllowlist,omitempty"`
	// +optional
	GloballyAllowedIPs *string `json:"globallyAllowedIps,omitempty"`
	// +optional
	GrafanaEnabled *bool `json:"grafanaEnabled,omitempty"`
	// +optional
	GrafanaURL *string `json:"grafanaUrl,omitempty"`
	// +optional
	GravatarEnabled *bool `json:"gravatarEnabled,omitempty"`
	// +optional
	GroupDownloadExportLimit *int64 `json:"groupDownloadExportLimit,omitempty"`
	// +optional
	GroupExportLimit *int64 `json:"groupExportLimit,omitempty"`
	// +optional
	GroupImportLimit *int64 `json:"groupImportLimit,omitempty"`
	// +optional
	GroupOwnersCanManageDefaultBranchProtection *bool `json:"groupOwnersCanManageDefaultBranchProtection,omitempty"`
	// +optional
	GroupRunnerTokenExpirationInterval *int64 `json:"groupRunnerTokenExpirationInterval,omitempty"`
	// +optional
	HTMLEmailsEnabled *bool `json:"htmlEmailsEnabled,omitempty"`
	// +optional
	HashedStorageEnabled *bool `json:"hashedStorageEnabled,omitempty"`
	// +optional
	HelpPageDocumentationBaseURL *string `json:"helpPageDocumentationBaseUrl,omitempty"`
	// +optional
	HelpPageHideCommercialContent *bool `json:"helpPageHideCommercialContent,omitempty"`
	// +optional
	HelpPageSupportURL *string `json:"helpPageSupportUrl,omitempty"`
	// +optional
	HelpPageText *string `json:"helpPageText,omitempty"`
	// +optional
	HelpText *string `json:"helpText,omitempty"`
	// +optional
	HideThirdPartyOffers *bool `json:"hideThirdPartyOffers,omitempty"`
	// +optional
	HomePageURL *string `json:"homePageUrl,omitempty"`
	// +optional
	HousekeepingEnabled *bool `json:"housekeepingEnabled,omitempty"`
	// +optional
	HousekeepingOptimizeRepositoryPeriod *int64 `json:"housekeepingOptimizeRepositoryPeriod,omitempty"`
	// +optional
	ImportSources *[]string `json:"importSources,omitempty"`
	// +optional
	InactiveProjectsDeleteAfterMonths *int64 `json:"inactiveProjectsDeleteAfterMonths,omitempty"`
	// +optional
	InactiveProjectsMinSizeMB *int64 `json:"inactiveProjectsMinSizeMB,omitempty"`
	// +optional
	InactiveProjectsSendWarningEmailAfterMonths *int64 `json:"inactiveProjectsSendWarningEmailAfterMonths,omitempty"`
	// +optional
	IncludeOptionalMetricsInServicePing *bool `json:"includeOptionalMetricsInServicePing,omitempty"`
	// +optional
	InProductMarketingEmailsEnabled *bool `json:"inProductMarketingEmailsEnabled,omitempty"`
	// +optional
	InvisibleCaptchaEnabled *bool `json:"invisibleCaptchaEnabled,omitempty"`
	// +optional
	IssuesCreateLimit *int64 `json:"issuesCreateLimit,omitempty"`
	// +optional
	JiraConnectApplicationKey *string `json:"jiraConnectApplicationKey,omitempty"`
	// +optional
	JiraConnectApplicationKeySecretRef *xpv1.LocalSecretKeySelector `json:"jiraConnectApplicationKeySecretRef,omitempty"`
	// +optional
	JiraConnectPublicKeyStorageEnabled *bool `json:"jiraConnectPublicKeyStorageEnabled,omitempty"`
	// +optional
	JiraConnectProxyURL *string `json:"jiraConnectProxyUrl,omitempty"`
	// +optional
	KeepLatestArtifact *bool `json:"keepLatestArtifact,omitempty"`
	// +optional
	KrokiEnabled *bool `json:"krokiEnabled,omitempty"`
	// +optional
	KrokiFormats *map[string]bool `json:"krokiFormats,omitempty"`
	// +optional
	KrokiURL *string `json:"krokiUrl,omitempty"`
	// +optional
	LocalMarkdownVersion *int64 `json:"localMarkdownVersion,omitempty"`
	// +optional
	LockDuoFeaturesEnabled *bool `json:"lockDuoFeaturesEnabled,omitempty"`
	// +optional
	LockMembershipsToLDAP *bool `json:"lockMembershipsToLdap,omitempty"`
	// +optional
	LoginRecaptchaProtectionEnabled *bool `json:"loginRecaptchaProtectionEnabled,omitempty"`
	// +optional
	MailgunEventsEnabled *bool `json:"mailgunEventsEnabled,omitempty"`
	// +optional
	MailgunSigningKey *string `json:"mailgunSigningKey,omitempty"`
	// +optional
	MailgunSigningKeySecretRef *xpv1.LocalSecretKeySelector `json:"mailgunSigningKeySecretRef,omitempty"`
	// +optional
	MaintenanceMode *bool `json:"maintenanceMode,omitempty"`
	// +optional
	MaintenanceModeMessage *string `json:"maintenanceModeMessage,omitempty"`
	// +optional
	MavenPackageRequestsForwarding *bool `json:"mavenPackageRequestsForwarding,omitempty"`
	// +optional
	MaxArtifactsSize *int64 `json:"maxArtifactsSize,omitempty"`
	// +optional
	MaxAttachmentSize *int64 `json:"maxAttachmentSize,omitempty"`
	// +optional
	MaxDecompressedArchiveSize *int64 `json:"maxDecompressedArchiveSize,omitempty"`
	// +optional
	MaxExportSize *int64 `json:"maxExportSize,omitempty"`
	// +optional
	MaxImportRemoteFileSize *int64 `json:"maxImportRemoteFileSize,omitempty"`
	// +optional
	MaxImportSize *int64 `json:"maxImportSize,omitempty"`
	// +optional
	MaxLoginAttempts *int64 `json:"maxLoginAttempts,omitempty"`
	// +optional
	MaxNumberOfRepositoryDownloads *int64 `json:"maxNumberOfRepositoryDownloads,omitempty"`
	// +optional
	MaxNumberOfRepositoryDownloadsWithinTimePeriod *int64 `json:"maxNumberOfRepositoryDownloadsWithinTimePeriod,omitempty"`
	// +optional
	MaxPagesSize *int64 `json:"maxPagesSize,omitempty"`
	// +optional
	MaxPersonalAccessTokenLifetime *int64 `json:"maxPersonalAccessTokenLifetime,omitempty"`
	// +optional
	MaxSSHKeyLifetime *int64 `json:"maxSshKeyLifetime,omitempty"`
	// +optional
	MaxTerraformStateSizeBytes *int64 `json:"maxTerraformStateSizeBytes,omitempty"`
	// +optional
	MaxYAMLDepth *int64 `json:"maxYamlDepth,omitempty"`
	// +optional
	MaxYAMLSizeBytes *int64 `json:"maxYamlSizeBytes,omitempty"`
	// +optional
	MetricsMethodCallThreshold *int64 `json:"metricsMethodCallThreshold,omitempty"`
	// +optional
	MinimumPasswordLength *int64 `json:"minimumPasswordLength,omitempty"`
	// +optional
	MirrorAvailable *bool `json:"mirrorAvailable,omitempty"`
	// +optional
	MirrorCapacityThreshold *int64 `json:"mirrorCapacityThreshold,omitempty"`
	// +optional
	MirrorMaxCapacity *int64 `json:"mirrorMaxCapacity,omitempty"`
	// +optional
	MirrorMaxDelay *int64 `json:"mirrorMaxDelay,omitempty"`
	// +optional
	NPMPackageRequestsForwarding *bool `json:"npmPackageRequestsForwarding,omitempty"`
	// +optional
	NotesCreateLimit *int64 `json:"notesCreateLimit,omitempty"`
	// +optional
	NotifyOnUnknownSignIn *bool `json:"notifyOnUnknownSignIn,omitempty"`
	// +optional
	NugetSkipMetadataURLValidation *bool `json:"nugetSkipMetadataUrlValidation,omitempty"`
	// +optional
	OutboundLocalRequestsAllowlistRaw *string `json:"outboundLocalRequestsAllowlistRaw,omitempty"`
	// +optional
	OutboundLocalRequestsWhitelist *[]string `json:"outboundLocalRequestsWhitelist,omitempty"`
	// +optional
	PackageMetadataPURLTypes *[]int64 `json:"packageMetadataPUrlTypes,omitempty"`
	// +optional
	PackageRegistryAllowAnyoneToPullOption *bool `json:"packageRegistryAllowAnyoneToPullOption,omitempty"`
	// +optional
	PackageRegistryCleanupPoliciesWorkerCapacity *int64 `json:"packageRegistryCleanupPoliciesWorkerCapacity,omitempty"`
	// +optional
	PagesDomainVerificationEnabled *bool `json:"pagesDomainVerificationEnabled,omitempty"`
	// +optional
	PasswordAuthenticationEnabledForGit *bool `json:"passwordAuthenticationEnabledForGit,omitempty"`
	// +optional
	PasswordAuthenticationEnabledForWeb *bool `json:"passwordAuthenticationEnabledForWeb,omitempty"`
	// +optional
	PasswordNumberRequired *bool `json:"passwordNumberRequired,omitempty"`
	// +optional
	PasswordSymbolRequired *bool `json:"passwordSymbolRequired,omitempty"`
	// +optional
	PasswordUppercaseRequired *bool `json:"passwordUppercaseRequired,omitempty"`
	// +optional
	PasswordLowercaseRequired *bool `json:"passwordLowercaseRequired,omitempty"`
	// +optional
	PerformanceBarAllowedGroupPath *string `json:"performanceBarAllowedGroupPath,omitempty"`
	// +optional
	PersonalAccessTokenPrefix *string `json:"personalAccessTokenPrefix,omitempty"`
	// +optional
	PlantumlEnabled *bool `json:"plantumlEnabled,omitempty"`
	// +optional
	PlantumlURL *string `json:"plantumlUrl,omitempty"`
	// +optional
	PipelineLimitPerProjectUserSha *int64 `json:"pipelineLimitPerProjectUserSha,omitempty"`
	// +optional
	PollingIntervalMultiplier *float64 `json:"pollingIntervalMultiplier,omitempty"`
	// +optional
	PreventMergeRequestsAuthorApproval *bool `json:"preventMergeRequestsAuthorApproval,omitempty"`
	// +optional
	PreventMergeRequestsCommittersApproval *bool `json:"preventMergeRequestsCommittersApproval,omitempty"`
	// +optional
	ProjectDownloadExportLimit *int64 `json:"projectDownloadExportLimit,omitempty"`
	// +optional
	ProjectExportEnabled *bool `json:"projectExportEnabled,omitempty"`
	// +optional
	ProjectExportLimit *int64 `json:"projectExportLimit,omitempty"`
	// +optional
	ProjectImportLimit *int64 `json:"projectImportLimit,omitempty"`
	// +optional
	ProjectJobsAPIRateLimit *int64 `json:"projectJobsApiRateLimit,omitempty"`
	// +optional
	ProjectRunnerTokenExpirationInterval *int64 `json:"projectRunnerTokenExpirationInterval,omitempty"`
	// +optional
	ProjectsAPIRateLimitUnauthenticated *int64 `json:"projectsApiRateLimitUnauthenticated,omitempty"`
	// +optional
	PrometheusMetricsEnabled *bool `json:"prometheusMetricsEnabled,omitempty"`
	// +optional
	ProtectedCIVariables *bool `json:"protectedCIVariables,omitempty"`
	// +optional
	PseudonymizerEnabled *bool `json:"pseudonymizerEnabled,omitempty"`
	// +optional
	PushEventActivitiesLimit *int64 `json:"pushEventActivitiesLimit,omitempty"`
	// +optional
	PushEventHooksLimit *int64 `json:"pushEventHooksLimit,omitempty"`
	// +optional
	PyPIPackageRequestsForwarding *bool `json:"pyPIpackageRequestsForwarding,omitempty"`
	// +optional
	RSAKeyRestriction *int64 `json:"rsaKeyRestriction,omitempty"`
	// +optional
	RateLimitingResponseText *string `json:"rateLimitingResponseText,omitempty"`
	// +optional
	RawBlobRequestLimit *int64 `json:"rawBlobRequestLimit,omitempty"`
	// +optional
	RecaptchaEnabled *bool `json:"recaptchaEnabled,omitempty"`
	// +optional
	RecaptchaPrivateKey *string `json:"recaptchaPrivateKey,omitempty"`
	// +optional
	RecaptchaPrivateKeySecretRef *xpv1.LocalSecretKeySelector `json:"recaptchaPrivateKeySecretRef,omitempty"`
	// +optional
	RecaptchaSiteKey *string `json:"recaptchaSiteKey,omitempty"`
	// +optional
	RecaptchaSiteKeySecretRef *xpv1.LocalSecretKeySelector `json:"recaptchaSiteKeySecretRef,omitempty"`
	// +optional
	ReceiveMaxInputSize *int64 `json:"receiveMaxInputSize,omitempty"`
	// +optional
	ReceptiveClusterAgentsEnabled *bool `json:"receptiveClusterAgentsEnabled,omitempty"`
	// +optional
	RememberMeEnabled *bool `json:"rememberMeEnabled,omitempty"`
	// +optional
	RepositoryChecksEnabled *bool `json:"repositoryChecksEnabled,omitempty"`
	// +optional
	RepositorySizeLimit *int64 `json:"repositorySizeLimit,omitempty"`
	// +optional
	RepositoryStorages *[]string `json:"repositoryStorages,omitempty"`
	// +optional
	RepositoryStoragesWeighted *map[string]int64 `json:"repositoryStoragesWeighted,omitempty"`
	// +optional
	RequireAdminApprovalAfterUserSignup *bool `json:"requireAdminApprovalAfterUserSignup,omitempty"`
	// +optional
	RequireAdminTwoFactorAuthentication *bool `json:"requireAdminTwoFactorAuthentication,omitempty"`
	// +optional
	RequirePersonalAccessTokenExpiry *bool `json:"requirePersonalAccessTokenExpiry,omitempty"`
	// +optional
	RequireTwoFactorAuthentication *bool `json:"requireTwoFactorAuthentication,omitempty"`
	// +optional
	RestrictedVisibilityLevels *[]string `json:"restrictedVisibilityLevels,omitempty"`
	// +optional
	RunnerTokenExpirationInterval *int64 `json:"runnerTokenExpirationInterval,omitempty"`
	// +optional
	SearchRateLimit *int64 `json:"searchRateLimit,omitempty"`
	// +optional
	SearchRateLimitUnauthenticated *int64 `json:"searchRateLimitUnauthenticated,omitempty"`
	// +optional
	SecretDetectionRevocationTokenTypesURL *string `json:"secretDetectionRevocationTokenTypesUrl,omitempty"`
	// +optional
	SecretDetectionTokenRevocationEnabled *bool `json:"secretDetectionTokenRevocationEnabled,omitempty"`
	// +optional
	SecretDetectionTokenRevocationToken *string `json:"secretDetectionTokenRevocationToken,omitempty"`
	// +optional
	SecretDetectionTokenRevocationTokenSecretRef *xpv1.LocalSecretKeySelector `json:"secretDetectionTokenRevocationTokenSecretRef,omitempty"`
	// +optional
	SecretDetectionTokenRevocationURL *string `json:"secretDetectionTokenRevocationUrl,omitempty"`
	// +optional
	SecurityApprovalPoliciesLimit *int64 `json:"securityApprovalPoliciesLimit,omitempty"`
	// +optional
	SecurityPolicyGlobalGroupApproversEnabled *bool `json:"securityPolicyGlobalGroupApproversEnabled,omitempty"`
	// +optional
	SecurityTXTContent *string `json:"securityTXTContent,omitempty"`
	// +optional
	SendUserConfirmationEmail *bool `json:"sendUserConfirmationEmail,omitempty"`
	// +optional
	SentryClientsideDSN *string `json:"sentryClientsideDSN,omitempty"`
	// +optional
	SentryDSN *string `json:"sentryDSN,omitempty"`
	// +optional
	SentryEnabled *string `json:"sentryEnabled,omitempty"`
	// +optional
	SentryEnvironment *string `json:"sentryEnvironment,omitempty"`
	// +optional
	ServiceAccessTokensExpirationEnforced *bool `json:"serviceAccessTokensExpirationEnforced,omitempty"`
	// +optional
	SessionExpireDelay *int64 `json:"sessionExpireDelay,omitempty"`
	// +optional
	SharedRunnersEnabled *bool `json:"sharedRunnersEnabled,omitempty"`
	// +optional
	SharedRunnersMinutes *int64 `json:"sharedRunnersMinutes,omitempty"`
	// +optional
	SharedRunnersText *string `json:"sharedRunnersText,omitempty"`
	// +optional
	SidekiqJobLimiterCompressionThresholdBytes *int64 `json:"sidekiqJobLimiterCompressionThresholdBytes,omitempty"`
	// +optional
	SidekiqJobLimiterLimitBytes *int64 `json:"sidekiqJobLimiterLimitBytes,omitempty"`
	// +optional
	SidekiqJobLimiterMode *string `json:"sidekiqJobLimiterMode,omitempty"`
	// +optional
	SignInText *string `json:"signInText,omitempty"`
	// +optional
	SignupEnabled *bool `json:"signupEnabled,omitempty"`
	// +optional
	SilentAdminExportsEnabled *bool `json:"silentAdminExportsEnabled,omitempty"`
	// +optional
	SilentModeEnabled *bool `json:"silentModeEnabled,omitempty"`
	// +optional
	SlackAppEnabled *bool `json:"slackAppEnabled,omitempty"`
	// +optional
	SlackAppID *string `json:"slackAppId,omitempty"`
	// +optional
	SlackAppSecret *string `json:"slackAppSecret,omitempty"`
	// +optional
	SlackAppSecretSecretRef *xpv1.LocalSecretKeySelector `json:"slackAppSecretSecretRef,omitempty"`
	// +optional
	SlackAppSigningSecret *string `json:"slackAppSigningSecret,omitempty"`
	// +optional
	SlackAppSigningSecretSecretRef *xpv1.LocalSecretKeySelector `json:"slackAppSigningSecretSecretRef,omitempty"`
	// +optional
	SlackAppVerificationToken *string `json:"slackAppVerificationToken,omitempty"`
	// +optional
	SlackAppVerificationTokenSecretRef *xpv1.LocalSecretKeySelector `json:"slackAppVerificationTokenSecretRef,omitempty"`
	// +optional
	SnippetSizeLimit *int64 `json:"snippetSizeLimit,omitempty"`
	// +optional
	SnowplowAppID *string `json:"snowplowAppId,omitempty"`
	// +optional
	SnowplowCollectorHostname *string `json:"snowplowCollectorHostname,omitempty"`
	// +optional
	SnowplowCookieDomain *string `json:"snowplowCookieDomain,omitempty"`
	// +optional
	SnowplowDatabaseCollectorHostname *string `json:"snowplowDatabaseCollectorHostname,omitempty"`
	// +optional
	SnowplowEnabled *bool `json:"snowplowEnabled,omitempty"`
	// +optional
	SourcegraphEnabled *bool `json:"sourcegraphEnabled,omitempty"`
	// +optional
	SourcegraphPublicOnly *bool `json:"sourcegraphPublicOnly,omitempty"`
	// +optional
	SourcegraphURL *string `json:"sourcegraphUrl,omitempty"`
	// +optional
	SpamCheckAPIKey *string `json:"spamCheckApiKey,omitempty"`
	// +optional
	SpamCheckAPIKeySecretRef *xpv1.LocalSecretKeySelector `json:"spamCheckApiKeySecretRef,omitempty"`
	// +optional
	SpamCheckEndpointEnabled *bool `json:"spamCheckEndpointEnabled,omitempty"`
	// +optional
	SpamCheckEndpointURL *string `json:"spamCheckEndpointUrl,omitempty"`
	// +optional
	StaticObjectsExternalStorageAuthToken *string `json:"staticObjectsExternalStorageAuthToken,omitempty"`
	// +optional
	StaticObjectsExternalStorageAuthTokenSecretRef *xpv1.LocalSecretKeySelector `json:"staticObjectsExternalStorageAuthTokenSecretRef,omitempty"`
	// +optional
	StaticObjectsExternalStorageURL *string `json:"staticObjectsExternalStorageUrl,omitempty"`
	// +optional
	SuggestPipelineEnabled *bool `json:"suggestPipelineEnabled,omitempty"`
	// +optional
	TerminalMaxSessionTime *int64 `json:"terminalMaxSessionTime,omitempty"`
	// +optional
	Terms *string `json:"terms,omitempty"`
	// +optional
	ThrottleAuthenticatedAPIEnabled *bool `json:"throttleAuthenticatedApiEnabled,omitempty"`
	// +optional
	ThrottleAuthenticatedAPIPeriodInSeconds *int64 `json:"throttleAuthenticatedApiPeriodInSeconds,omitempty"`
	// +optional
	ThrottleAuthenticatedAPIRequestsPerPeriod *int64 `json:"throttleAuthenticatedApiRequestsPerPeriod,omitempty"`
	// +optional
	ThrottleAuthenticatedDeprecatedAPIEnabled *bool `json:"throttleAuthenticatedDeprecatedApiEnabled,omitempty"`
	// +optional
	ThrottleAuthenticatedDeprecatedAPIPeriodInSeconds *int64 `json:"throttleAuthenticatedDeprecatedApiPeriodInSeconds,omitempty"`
	// +optional
	ThrottleAuthenticatedDeprecatedAPIRequestsPerPeriod *int64 `json:"throttleAuthenticatedDeprecatedApiRequestsPerPeriod,omitempty"`
	// +optional
	ThrottleAuthenticatedFilesAPIEnabled *bool `json:"throttleAuthenticatedFilesApiEnabled,omitempty"`
	// +optional
	ThrottleAuthenticatedFilesAPIPeriodInSeconds *int64 `json:"throttleAuthenticatedFilesApiPeriodInSeconds,omitempty"`
	// +optional
	ThrottleAuthenticatedFilesAPIRequestsPerPeriod *int64 `json:"throttleAuthenticatedFilesApiRequestsPerPeriod,omitempty"`
	// +optional
	ThrottleAuthenticatedGitLFSEnabled *bool `json:"throttleAuthenticatedGitLFSEnabled,omitempty"`
	// +optional
	ThrottleAuthenticatedGitLFSPeriodInSeconds *int64 `json:"throttleAuthenticatedGitLFSPeriodInSeconds,omitempty"`
	// +optional
	ThrottleAuthenticatedGitLFSRequestsPerPeriod *int64 `json:"throttleAuthenticatedGitLFSRequestsPerPeriod,omitempty"`
	// +optional
	ThrottleAuthenticatedPackagesAPIEnabled *bool `json:"throttleAuthenticatedPackagesApiEnabled,omitempty"`
	// +optional
	ThrottleAuthenticatedPackagesAPIPeriodInSeconds *int64 `json:"throttleAuthenticatedPackagesApiPeriodInSeconds,omitempty"`
	// +optional
	ThrottleAuthenticatedPackagesAPIRequestsPerPeriod *int64 `json:"throttleAuthenticatedPackagesApiRequestsPerPeriod,omitempty"`
	// +optional
	ThrottleAuthenticatedWebEnabled *bool `json:"throttleAuthenticatedWebEnabled,omitempty"`
	// +optional
	ThrottleAuthenticatedWebPeriodInSeconds *int64 `json:"throttleAuthenticatedWebPeriodInSeconds,omitempty"`
	// +optional
	ThrottleAuthenticatedWebRequestsPerPeriod *int64 `json:"throttleAuthenticatedWebRequestsPerPeriod,omitempty"`
	// +optional
	ThrottleIncidentManagementNotificationEnabled *bool `json:"throttleIncidentManagementNotificationEnabled,omitempty"`
	// +optional
	ThrottleIncidentManagementNotificationPerPeriod *int64 `json:"throttleIncidentManagementNotificationPerPeriod,omitempty"`
	// +optional
	ThrottleIncidentManagementNotificationPeriodInSeconds *int64 `json:"throttleIncidentManagementNotificationPeriodInSeconds,omitempty"`
	// +optional
	ThrottleProtectedPathsEnabled *bool `json:"throttleProtectedPathsEnabled,omitempty"`
	// +optional
	ThrottleProtectedPathsPeriodInSeconds *int64 `json:"throttleProtectedPathsPeriodInSeconds,omitempty"`
	// +optional
	ThrottleProtectedPathsRequestsPerPeriod *int64 `json:"throttleProtectedPathsRequestsPerPeriod,omitempty"`
	// +optional
	ThrottleUnauthenticatedAPIEnabled *bool `json:"throttleUnauthenticatedApiEnabled,omitempty"`
	// +optional
	ThrottleUnauthenticatedAPIPeriodInSeconds *int64 `json:"throttleUnauthenticatedApiPeriodInSeconds,omitempty"`
	// +optional
	ThrottleUnauthenticatedAPIRequestsPerPeriod *int64 `json:"throttleUnauthenticatedApiRequestsPerPeriod,omitempty"`
	// +optional
	ThrottleUnauthenticatedDeprecatedAPIEnabled *bool `json:"throttleUnauthenticatedDeprecatedApiEnabled,omitempty"`
	// +optional
	ThrottleUnauthenticatedDeprecatedAPIPeriodInSeconds *int64 `json:"throttleUnauthenticatedDeprecatedApiPeriodInSeconds,omitempty"`
	// +optional
	ThrottleUnauthenticatedDeprecatedAPIRequestsPerPeriod *int64 `json:"throttleUnauthenticatedDeprecatedApiRequestsPerPeriod,omitempty"`
	// +optional
	ThrottleUnauthenticatedFilesAPIEnabled *bool `json:"throttleUnauthenticatedFilesApiEnabled,omitempty"`
	// +optional
	ThrottleUnauthenticatedFilesAPIPeriodInSeconds *int64 `json:"throttleUnauthenticatedFilesApiPeriodInSeconds,omitempty"`
	// +optional
	ThrottleUnauthenticatedFilesAPIRequestsPerPeriod *int64 `json:"throttleUnauthenticatedFilesApiRequestsPerPeriod,omitempty"`
	// +optional
	ThrottleUnauthenticatedGitLFSEnabled *bool `json:"throttleUnauthenticatedGitLFSEnabled,omitempty"`
	// +optional
	ThrottleUnauthenticatedGitLFSPeriodInSeconds *int64 `json:"throttleUnauthenticatedGitLFSPeriodInSeconds,omitempty"`
	// +optional
	ThrottleUnauthenticatedGitLFSRequestsPerPeriod *int64 `json:"throttleUnauthenticatedGitLFSRequestsPerPeriod,omitempty"`
	// +optional
	ThrottleUnauthenticatedPackagesAPIEnabled *bool `json:"throttleUnauthenticatedPackagesApiEnabled,omitempty"`
	// +optional
	ThrottleUnauthenticatedPackagesAPIPeriodInSeconds *int64 `json:"throttleUnauthenticatedPackagesApiPeriodInSeconds,omitempty"`
	// +optional
	ThrottleUnauthenticatedPackagesAPIRequestsPerPeriod *int64 `json:"throttleUnauthenticatedPackagesApiRequestsPerPeriod,omitempty"`
	// +optional
	ThrottleUnauthenticatedWebEnabled *bool `json:"throttleUnauthenticatedWebEnabled,omitempty"`
	// +optional
	ThrottleUnauthenticatedWebPeriodInSeconds *int64 `json:"throttleUnauthenticatedWebPeriodInSeconds,omitempty"`
	// +optional
	ThrottleUnauthenticatedWebRequestsPerPeriod *int64 `json:"throttleUnauthenticatedWebRequestsPerPeriod,omitempty"`
	// +optional
	TimeTrackingLimitToHours *bool `json:"timeTrackingLimitToHours,omitempty"`
	// +optional
	TwoFactorGracePeriod *int64 `json:"twoFactorGracePeriod,omitempty"`
	// +optional
	UnconfirmedUsersDeleteAfterDays *int64 `json:"unconfirmedUsersDeleteAfterDays,omitempty"`
	// +optional
	UniqueIPsLimitEnabled *bool `json:"uniqueIpsLimitEnabled,omitempty"`
	// +optional
	UniqueIPsLimitPerUser *int64 `json:"uniqueIpsLimitPerUser,omitempty"`
	// +optional
	UniqueIPsLimitTimeWindow *int64 `json:"uniqueIpsLimitTimeWindow,omitempty"`
	// +optional
	UpdateRunnerVersionsEnabled *bool `json:"updateRunnerVersionsEnabled,omitempty"`
	// +optional
	UpdatingNameDisabledForUsers *bool `json:"updatingNameDisabledForUsers,omitempty"`
	// +optional
	UsagePingEnabled *bool `json:"usagePingEnabled,omitempty"`
	// +optional
	UsagePingFeaturesEnabled *bool `json:"usagePingFeaturesEnabled,omitempty"`
	// +optional
	UseClickhouseForAnalytics *bool `json:"useClickhouseForAnalytics,omitempty"`
	// +optional
	UserDeactivationEmailsEnabled *bool `json:"userDeactivationEmailsEnabled,omitempty"`
	// +optional
	UserDefaultExternal *bool `json:"userDefaultExternal,omitempty"`
	// +optional
	UserDefaultInternalRegex *string `json:"userDefaultInternalRegex,omitempty"`
	// +optional
	UserDefaultsToPrivateProfile *bool `json:"userDefaultsToPrivateProfile,omitempty"`
	// +optional
	UserEmailLookupLimit *int64 `json:"userEmailLookupLimit,omitempty"`
	// +optional
	UserOauthApplications *bool `json:"userOauthApplications,omitempty"`
	// +optional
	UserShowAddSSHKeyMessage *bool `json:"userShowAddSshKeyMessage,omitempty"`
	// +optional
	UsersGetByIDLimit *int64 `json:"usersGetByIdLimit,omitempty"`
	// +optional
	UsersGetByIDLimitAllowlistRaw *string `json:"usersGetByIdLimitAllowlistRaw,omitempty"`
	// +optional
	ValidRunnerRegistrars *[]string `json:"validRunnerRegistrars,omitempty"`
	// +optional
	VersionCheckEnabled *bool `json:"versionCheckEnabled,omitempty"`
	// +optional
	WebIDEClientsidePreviewEnabled *bool `json:"webIdEClientsidePreviewEnabled,omitempty"`
	// +optional
	WhatsNewVariant *string `json:"whatsNewVariant,omitempty"`
	// +optional
	WikiPageMaxContentBytes *int64 `json:"wikiPageMaxContentBytes,omitempty"`
	// +optional
	AdminNotificationEmail *string `json:"adminNotificationEmail,omitempty"`
	// +optional
	AllowLocalRequestsFromHooksAndServices *bool `json:"allowLocalRequestsFromHooksAndServices,omitempty"`
	// +optional
	AssetProxyWhitelist *[]string `json:"assetProxyWhitelist,omitempty"`
	// +optional
	DefaultBranchProtection *int64 `json:"defaultBranchProtection,omitempty"`
	// +optional
	HousekeepingBitmapsEnabled *bool `json:"housekeepingBitmapsEnabled,omitempty"`
	// +optional
	HousekeepingFullRepackPeriod *int64 `json:"housekeepingFullRepackPeriod,omitempty"`
	// +optional
	HousekeepingGcPeriod *int64 `json:"housekeepingGcPeriod,omitempty"`
	// +optional
	HousekeepingIncrementalRepackPeriod *int64 `json:"housekeepingIncrementalRepackPeriod,omitempty"`
	// +optional
	PerformanceBarAllowedGroupID *int64 `json:"performanceBarAllowedGroupId,omitempty"`
	// +optional
	PerformanceBarEnabled *bool `json:"performanceBarEnabled,omitempty"`
	// +optional
	ThrottleUnauthenticatedEnabled *bool `json:"throttleUnauthenticatedEnabled,omitempty"`
	// +optional
	ThrottleUnauthenticatedPeriodInSeconds *int64 `json:"throttleUnauthenticatedPeriodInSeconds,omitempty"`
	// +optional
	ThrottleUnauthenticatedRequestsPerPeriod *int64 `json:"throttleUnauthenticatedRequestsPerPeriod,omitempty"`
}

// ApplicationSettingsObservation defines the observed state for ApplicationSettings
// This struct was generated from gitlab.Settings struct, with just a rework of the json tags.
type ApplicationSettingsObservation struct {
	// +optional
	ID int64 `json:"id,omitempty"`
	// +optional
	AbuseNotificationEmail string `json:"abuseNotificationEmail,omitempty"`
	// +optional
	AdminMode bool `json:"adminMode,omitempty"`
	// +optional
	AfterSignOutPath string `json:"afterSignOutPath,omitempty"`
	// +optional
	AfterSignUpText string `json:"afterSignUpText,omitempty"`
	// +optional
	AkismetEnabled bool `json:"akismetEnabled,omitempty"`
	// +optional
	AllowAccountDeletion bool `json:"allowAccountDeletion,omitempty"`
	// +optional
	AllowAllIntegrations bool `json:"allowAllIntegrations,omitempty"`
	// +optional
	AllowedIntegrations []string `json:"allowedIntegrations,omitempty"`
	// +optional
	AllowGroupOwnersToManageLDAP bool `json:"allowGroupOwnersToManageLdap,omitempty"`
	// +optional
	AllowLocalRequestsFromSystemHooks bool `json:"allowLocalRequestsFromSystemHooks,omitempty"`
	// +optional
	AllowLocalRequestsFromWebHooksAndServices bool `json:"allowLocalRequestsFromWebHooksAndServices,omitempty"`
	// +optional
	AllowProjectCreationForGuestAndBelow bool `json:"allowProjectCreationForGuestAndBelow,omitempty"`
	// +optional
	AllowRunnerRegistrationToken bool `json:"allowRunnerRegistrationToken,omitempty"`
	// +optional
	ArchiveBuildsInHumanReadable string `json:"archiveBuildsInHumanReadable,omitempty"`
	// +optional
	ASCIIDocMaxIncludes int64 `json:"asciiDocMaxIncludes,omitempty"`
	// +optional
	AssetProxyAllowlist []string `json:"assetProxyAllowlist,omitempty"`
	// +optional
	AssetProxyEnabled bool `json:"assetProxyEnabled,omitempty"`
	// +optional
	AssetProxyURL string `json:"assetProxyUrl,omitempty"`
	// +optional
	AuthorizedKeysEnabled bool `json:"authorizedKeysEnabled,omitempty"`
	// +optional
	AutoBanUserOnExcessiveProjectsDownload bool `json:"autoBanUserOnExcessiveProjectsDownload,omitempty"`
	// +optional
	AutocompleteUsers int64 `json:"autocompleteUsers,omitempty"`
	// +optional
	AutocompleteUsersUnauthenticated int64 `json:"autocompleteUsersUnauthenticated,omitempty"`
	// +optional
	AutoDevOpsDomain string `json:"autoDevOpsDomain,omitempty"`
	// +optional
	AutoDevOpsEnabled bool `json:"autoDevOpsEnabled,omitempty"`
	// +optional
	AutomaticPurchasedStorageAllocation bool `json:"automaticPurchasedStorageAllocation,omitempty"`
	// +optional
	BulkImportConcurrentPipelineBatchLimit int64 `json:"bulkImportConcurrentPipelineBatchLimit,omitempty"`
	// +optional
	BulkImportEnabled bool `json:"bulkImportEnabled,omitempty"`
	// +optional
	BulkImportMaxDownloadFileSize int64 `json:"bulkImportMaxDownloadFileSize,omitempty"`
	// +optional
	CanCreateGroup bool `json:"canCreateGroup,omitempty"`
	// +optional
	CheckNamespacePlan bool `json:"checkNamespacePlan,omitempty"`
	// +optional
	CIJobLiveTraceEnabled bool `json:"ciJobLiveTraceEnabled,omitempty"`
	// +optional
	CIMaxIncludes int64 `json:"ciMaxIncludes,omitempty"`
	// +optional
	CIMaxTotalYAMLSizeBytes int64 `json:"ciMaxTotalYamlSizeBytes,omitempty"`
	// +optional
	CIPartitionsSizeLimit int64 `json:"ciPartitionsSizeLimit,omitempty"`
	// +optional
	CommitEmailHostname string `json:"commitEmailHostname,omitempty"`
	// +optional
	ConcurrentBitbucketImportJobsLimit int64 `json:"concurrentBitbucketImportJobsLimit,omitempty"`
	// +optional
	ConcurrentBitbucketServerImportJobsLimit int64 `json:"concurrentBitbucketServerImportJobsLimit,omitempty"`
	// +optional
	ConcurrentGitHubImportJobsLimit int64 `json:"concurrentGitHubImportJobsLimit,omitempty"`
	// +optional
	ContainerExpirationPoliciesEnableHistoricEntries bool `json:"containerExpirationPoliciesEnableHistoricEntries,omitempty"`
	// +optional
	ContainerRegistryCleanupTagsServiceMaxListSize int64 `json:"containerRegistryCleanupTagsServiceMaxListSize,omitempty"`
	// +optional
	ContainerRegistryDeleteTagsServiceTimeout int64 `json:"containerRegistryDeleteTagsServiceTimeout,omitempty"`
	// +optional
	ContainerRegistryExpirationPoliciesCaching bool `json:"containerRegistryExpirationPoliciesCaching,omitempty"`
	// +optional
	ContainerRegistryExpirationPoliciesWorkerCapacity int64 `json:"containerRegistryExpirationPoliciesWorkerCapacity,omitempty"`
	// +optional
	ContainerRegistryImportCreatedBefore *metav1.Time `json:"containerRegistryImportCreatedBefore,omitempty"`
	// +optional
	ContainerRegistryImportMaxRetries int64 `json:"containerRegistryImportMaxRetries,omitempty"`
	// +optional
	ContainerRegistryImportMaxStepDuration int64 `json:"containerRegistryImportMaxStepDuration,omitempty"`
	// +optional
	ContainerRegistryImportMaxTagsCount int64 `json:"containerRegistryImportMaxTagsCount,omitempty"`
	// +optional
	ContainerRegistryImportStartMaxRetries int64 `json:"containerRegistryImportStartMaxRetries,omitempty"`
	// +optional
	ContainerRegistryImportTargetPlan string `json:"containerRegistryImportTargetPlan,omitempty"`
	// +optional
	ContainerRegistryTokenExpireDelay int64 `json:"containerRegistryTokenExpireDelay,omitempty"`
	// +optional
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// +optional
	CustomHTTPCloneURLRoot string `json:"customHTTPCloneUrlRoot,omitempty"`
	// +optional
	DNSRebindingProtectionEnabled bool `json:"dnsRebindingProtectionEnabled,omitempty"`
	// +optional
	DSAKeyRestriction int64 `json:"dsaKeyRestriction,omitempty"`
	// +optional
	DeactivateDormantUsers bool `json:"deactivateDormantUsers,omitempty"`
	// +optional
	DeactivateDormantUsersPeriod int64 `json:"deactivateDormantUsersPeriod,omitempty"`
	// +optional
	DecompressArchiveFileTimeout int64 `json:"decompressArchiveFileTimeout,omitempty"`
	// +optional
	DefaultArtifactsExpireIn string `json:"defaultArtifactsExpireIn,omitempty"`
	// +optional
	DefaultBranchName string `json:"defaultBranchName,omitempty"`
	// +optional
	DefaultBranchProtectionDefaults *BranchProtectionDefaults `json:"defaultBranchProtectionDefaults,omitempty"`
	// +optional
	DefaultCiConfigPath string `json:"defaultCiConfigPath,omitempty"`
	// +optional
	DefaultGroupVisibility string `json:"defaultGroupVisibility,omitempty"`
	// +optional
	DefaultPreferredLanguage string `json:"defaultPreferredLanguage,omitempty"`
	// +optional
	DefaultProjectCreation int64 `json:"defaultProjectCreation,omitempty"`
	// +optional
	DefaultProjectDeletionProtection bool `json:"defaultProjectDeletionProtection,omitempty"`
	// +optional
	DefaultProjectVisibility string `json:"defaultProjectVisibility,omitempty"`
	// +optional
	DefaultProjectsLimit int64 `json:"defaultProjectsLimit,omitempty"`
	// +optional
	DefaultSnippetVisibility string `json:"defaultSnippetVisibility,omitempty"`
	// +optional
	DefaultSyntaxHighlightingTheme int64 `json:"defaultSyntaxHighlightingTheme,omitempty"`
	// +optional
	DelayedGroupDeletion bool `json:"delayedGroupDeletion,omitempty"`
	// +optional
	DelayedProjectDeletion bool `json:"delayedProjectDeletion,omitempty"`
	// +optional
	DeleteInactiveProjects bool `json:"deleteInactiveProjects,omitempty"`
	// +optional
	DeleteUnconfirmedUsers bool `json:"deleteUnconfirmedUsers,omitempty"`
	// +optional
	DeletionAdjournedPeriod int64 `json:"deletionAdjournedPeriod,omitempty"`
	// +optional
	DiagramsnetEnabled bool `json:"diagramsnetEnabled,omitempty"`
	// +optional
	DiagramsnetURL string `json:"diagramsnetUrl,omitempty"`
	// +optional
	DiffMaxFiles int64 `json:"diffMaxFiles,omitempty"`
	// +optional
	DiffMaxLines int64 `json:"diffMaxLines,omitempty"`
	// +optional
	DiffMaxPatchBytes int64 `json:"diffMaxPatchBytes,omitempty"`
	// +optional
	DisableAdminOAuthScopes bool `json:"disableAdminOAuthScopes,omitempty"`
	// +optional
	DisableFeedToken bool `json:"disableFeedToken,omitempty"`
	// +optional
	DisableOverridingApproversPerMergeRequest bool `json:"disableOverridingApproversPerMergeRequest,omitempty"`
	// +optional
	DisablePersonalAccessTokens bool `json:"disablePersonalAccessTokens,omitempty"`
	// +optional
	DisabledOauthSignInSources []string `json:"disabledOauthSignInSources,omitempty"`
	// +optional
	DomainAllowlist []string `json:"domainAllowlist,omitempty"`
	// +optional
	DomainDenylist []string `json:"domainDenylist,omitempty"`
	// +optional
	DomainDenylistEnabled bool `json:"domainDenylistEnabled,omitempty"`
	// +optional
	DownstreamPipelineTriggerLimitPerProjectUserSHA int64 `json:"downstreamPipelineTriggerLimitPerProjectUserSHA,omitempty"`
	// +optional
	DuoFeaturesEnabled bool `json:"duoFeaturesEnabled,omitempty"`
	// +optional
	ECDSAKeyRestriction int64 `json:"ecdsaKeyRestriction,omitempty"`
	// +optional
	ECDSASKKeyRestriction int64 `json:"ecdsaskKeyRestriction,omitempty"`
	// +optional
	EKSAccountID string `json:"eksAccountId,omitempty"`
	// +optional
	EKSIntegrationEnabled bool `json:"eksIntegrationEnabled,omitempty"`
	// +optional
	Ed25519KeyRestriction int64 `json:"ed25519KeyRestriction,omitempty"`
	// +optional
	Ed25519SKKeyRestriction int64 `json:"ed25519SKKeyRestriction,omitempty"`
	// +optional
	ElasticsearchAWS bool `json:"elasticsearchAws,omitempty"`
	// +optional
	ElasticsearchAWSRegion string `json:"elasticsearchAwsRegion,omitempty"`
	// +optional
	ElasticsearchAnalyzersKuromojiEnabled bool `json:"elasticsearchAnalyzersKuromojiEnabled,omitempty"`
	// +optional
	ElasticsearchAnalyzersKuromojiSearch bool `json:"elasticsearchAnalyzersKuromojiSearch,omitempty"`
	// +optional
	ElasticsearchAnalyzersSmartCNEnabled bool `json:"elasticsearchAnalyzersSmartCnEnabled,omitempty"`
	// +optional
	ElasticsearchAnalyzersSmartCNSearch bool `json:"elasticsearchAnalyzersSmartCnSearch,omitempty"`
	// +optional
	ElasticsearchClientRequestTimeout int64 `json:"elasticsearchClientRequestTimeout,omitempty"`
	// +optional
	ElasticsearchIndexedFieldLengthLimit int64 `json:"elasticsearchIndexedFieldLengthLimit,omitempty"`
	// +optional
	ElasticsearchIndexedFileSizeLimitKB int64 `json:"elasticsearchIndexedFileSizeLimitKB,omitempty"`
	// +optional
	ElasticsearchIndexing bool `json:"elasticsearchIndexing,omitempty"`
	// +optional
	ElasticsearchLimitIndexing bool `json:"elasticsearchLimitIndexing,omitempty"`
	// +optional
	ElasticsearchMaxBulkConcurrency int64 `json:"elasticsearchMaxBulkConcurrency,omitempty"`
	// +optional
	ElasticsearchMaxBulkSizeMB int64 `json:"elasticsearchMaxBulkSizeMB,omitempty"`
	// +optional
	ElasticsearchMaxCodeIndexingConcurrency int64 `json:"elasticsearchMaxCodeIndexingConcurrency,omitempty"`
	// +optional
	ElasticsearchNamespaceIDs []int64 `json:"elasticsearchNamespaceIds,omitempty"`
	// +optional
	ElasticsearchPauseIndexing bool `json:"elasticsearchPauseIndexing,omitempty"`
	// +optional
	ElasticsearchProjectIDs []int64 `json:"elasticsearchProjectIds,omitempty"`
	// +optional
	ElasticsearchReplicas int64 `json:"elasticsearchReplicas,omitempty"`
	// +optional
	ElasticsearchRequeueWorkers bool `json:"elasticsearchRequeueWorkers,omitempty"`
	// +optional
	ElasticsearchRetryOnFailure int64 `json:"elasticsearchRetryOnFailure,omitempty"`
	// +optional
	ElasticsearchSearch bool `json:"elasticsearchSearch,omitempty"`
	// +optional
	ElasticsearchShards int64 `json:"elasticsearchShards,omitempty"`
	// +optional
	ElasticsearchURL []string `json:"elasticsearchUrl,omitempty"`
	// +optional
	ElasticsearchUsername string `json:"elasticsearchUsername,omitempty"`
	// +optional
	ElasticsearchWorkerNumberOfShards int64 `json:"elasticsearchWorkerNumberOfShards,omitempty"`
	// +optional
	EmailAdditionalText string `json:"emailAdditionalText,omitempty"`
	// +optional
	EmailAuthorInBody bool `json:"emailAuthorInBody,omitempty"`
	// +optional
	EmailConfirmationSetting string `json:"emailConfirmationSetting,omitempty"`
	// +optional
	EmailRestrictions string `json:"emailRestrictions,omitempty"`
	// +optional
	EmailRestrictionsEnabled bool `json:"emailRestrictionsEnabled,omitempty"`
	// +optional
	EnableArtifactExternalRedirectWarningPage bool `json:"enableArtifactExternalRedirectWarningPage,omitempty"`
	// +optional
	EnabledGitAccessProtocol string `json:"enabledGitAccessProtocol,omitempty"`
	// +optional
	EnforceCIInboundJobTokenScopeEnabled bool `json:"enforceCIInboundJobTokenScopeEnabled,omitempty"`
	// +optional
	EnforceNamespaceStorageLimit bool `json:"enforceNamespaceStorageLimit,omitempty"`
	// +optional
	EnforcePATExpiration bool `json:"enforcePATExpiration,omitempty"`
	// +optional
	EnforceSSHKeyExpiration bool `json:"enforceSshKeyExpiration,omitempty"`
	// +optional
	EnforceTerms bool `json:"enforceTerms,omitempty"`
	// +optional
	ExternalAuthClientCert string `json:"externalAuthClientCert,omitempty"`
	// +optional
	ExternalAuthClientKeyPass string `json:"externalAuthClientKeyPass,omitempty"`
	// +optional
	ExternalAuthorizationServiceDefaultLabel string `json:"externalAuthorizationServiceDefaultLabel,omitempty"`
	// +optional
	ExternalAuthorizationServiceEnabled bool `json:"externalAuthorizationServiceEnabled,omitempty"`
	// +optional
	ExternalAuthorizationServiceTimeout float64 `json:"externalAuthorizationServiceTimeout,omitempty"`
	// +optional
	ExternalAuthorizationServiceURL string `json:"externalAuthorizationServiceUrl,omitempty"`
	// +optional
	ExternalPipelineValidationServiceTimeout int64 `json:"externalPipelineValidationServiceTimeout,omitempty"`
	// +optional
	ExternalPipelineValidationServiceURL string `json:"externalPipelineValidationServiceUrl,omitempty"`
	// +optional
	FailedLoginAttemptsUnlockPeriodInMinutes int64 `json:"failedLoginAttemptsUnlockPeriodInMinutes,omitempty"`
	// +optional
	FileTemplateProjectID int64 `json:"fileTemplateProjectId,omitempty"`
	// +optional
	FirstDayOfWeek int64 `json:"firstDayOfWeek,omitempty"`
	// +optional
	FlocEnabled bool `json:"flocEnabled,omitempty"`
	// +optional
	GeoNodeAllowedIPs string `json:"geoNodeAllowedIps,omitempty"`
	// +optional
	GeoStatusTimeout int64 `json:"geoStatusTimeout,omitempty"`
	// +optional
	GitRateLimitUsersAlertlist []int64 `json:"gitRateLimitUsersAlertlist,omitempty"`
	// +optional
	GitTwoFactorSessionExpiry int64 `json:"gitTwoFactorSessionExpiry,omitempty"`
	// +optional
	GitalyTimeoutDefault int64 `json:"gitalyTimeoutDefault,omitempty"`
	// +optional
	GitalyTimeoutFast int64 `json:"gitalyTimeoutFast,omitempty"`
	// +optional
	GitalyTimeoutMedium int64 `json:"gitalyTimeoutMedium,omitempty"`
	// +optional
	GitlabDedicatedInstance bool `json:"gitlabDedicatedInstance,omitempty"`
	// +optional
	GitlabEnvironmentToolkitInstance bool `json:"gitlabEnvironmentToolkitInstance,omitempty"`
	// +optional
	GitlabShellOperationLimit int64 `json:"gitlabShellOperationLimit,omitempty"`
	// +optional
	GitpodEnabled bool `json:"gitpodEnabled,omitempty"`
	// +optional
	GitpodURL string `json:"gitpodUrl,omitempty"`
	// +optional
	GitRateLimitUsersAllowlist []string `json:"gitRateLimitUsersAllowlist,omitempty"`
	// +optional
	GloballyAllowedIPs string `json:"globallyAllowedIps,omitempty"`
	// +optional
	GrafanaEnabled bool `json:"grafanaEnabled,omitempty"`
	// +optional
	GrafanaURL string `json:"grafanaUrl,omitempty"`
	// +optional
	GravatarEnabled bool `json:"gravatarEnabled,omitempty"`
	// +optional
	GroupDownloadExportLimit int64 `json:"groupDownloadExportLimit,omitempty"`
	// +optional
	GroupExportLimit int64 `json:"groupExportLimit,omitempty"`
	// +optional
	GroupImportLimit int64 `json:"groupImportLimit,omitempty"`
	// +optional
	GroupOwnersCanManageDefaultBranchProtection bool `json:"groupOwnersCanManageDefaultBranchProtection,omitempty"`
	// +optional
	GroupRunnerTokenExpirationInterval int64 `json:"groupRunnerTokenExpirationInterval,omitempty"`
	// +optional
	HTMLEmailsEnabled bool `json:"htmlEmailsEnabled,omitempty"`
	// +optional
	HashedStorageEnabled bool `json:"hashedStorageEnabled,omitempty"`
	// +optional
	HelpPageDocumentationBaseURL string `json:"helpPageDocumentationBaseUrl,omitempty"`
	// +optional
	HelpPageHideCommercialContent bool `json:"helpPageHideCommercialContent,omitempty"`
	// +optional
	HelpPageSupportURL string `json:"helpPageSupportUrl,omitempty"`
	// +optional
	HelpPageText string `json:"helpPageText,omitempty"`
	// +optional
	HelpText string `json:"helpText,omitempty"`
	// +optional
	HideThirdPartyOffers bool `json:"hideThirdPartyOffers,omitempty"`
	// +optional
	HomePageURL string `json:"homePageUrl,omitempty"`
	// +optional
	HousekeepingEnabled bool `json:"housekeepingEnabled,omitempty"`
	// +optional
	HousekeepingOptimizeRepositoryPeriod int64 `json:"housekeepingOptimizeRepositoryPeriod,omitempty"`
	// +optional
	ImportSources []string `json:"importSources,omitempty"`
	// +optional
	InactiveProjectsDeleteAfterMonths int64 `json:"inactiveProjectsDeleteAfterMonths,omitempty"`
	// +optional
	InactiveProjectsMinSizeMB int64 `json:"inactiveProjectsMinSizeMB,omitempty"`
	// +optional
	InactiveProjectsSendWarningEmailAfterMonths int64 `json:"inactiveProjectsSendWarningEmailAfterMonths,omitempty"`
	// +optional
	IncludeOptionalMetricsInServicePing bool `json:"includeOptionalMetricsInServicePing,omitempty"`
	// +optional
	InProductMarketingEmailsEnabled bool `json:"inProductMarketingEmailsEnabled,omitempty"`
	// +optional
	InvisibleCaptchaEnabled bool `json:"invisibleCaptchaEnabled,omitempty"`
	// +optional
	IssuesCreateLimit int64 `json:"issuesCreateLimit,omitempty"`
	// +optional
	JiraConnectPublicKeyStorageEnabled bool `json:"jiraConnectPublicKeyStorageEnabled,omitempty"`
	// +optional
	JiraConnectProxyURL string `json:"jiraConnectProxyUrl,omitempty"`
	// +optional
	KeepLatestArtifact bool `json:"keepLatestArtifact,omitempty"`
	// +optional
	KrokiEnabled bool `json:"krokiEnabled,omitempty"`
	// +optional
	KrokiFormats map[string]bool `json:"krokiFormats,omitempty"`
	// +optional
	KrokiURL string `json:"krokiUrl,omitempty"`
	// +optional
	LocalMarkdownVersion int64 `json:"localMarkdownVersion,omitempty"`
	// +optional
	LockDuoFeaturesEnabled bool `json:"lockDuoFeaturesEnabled,omitempty"`
	// +optional
	LockMembershipsToLDAP bool `json:"lockMembershipsToLdap,omitempty"`
	// +optional
	LoginRecaptchaProtectionEnabled bool `json:"loginRecaptchaProtectionEnabled,omitempty"`
	// +optional
	MailgunEventsEnabled bool `json:"mailgunEventsEnabled,omitempty"`
	// +optional
	MaintenanceMode bool `json:"maintenanceMode,omitempty"`
	// +optional
	MaintenanceModeMessage string `json:"maintenanceModeMessage,omitempty"`
	// +optional
	MavenPackageRequestsForwarding bool `json:"mavenPackageRequestsForwarding,omitempty"`
	// +optional
	MaxArtifactsSize int64 `json:"maxArtifactsSize,omitempty"`
	// +optional
	MaxAttachmentSize int64 `json:"maxAttachmentSize,omitempty"`
	// +optional
	MaxDecompressedArchiveSize int64 `json:"maxDecompressedArchiveSize,omitempty"`
	// +optional
	MaxExportSize int64 `json:"maxExportSize,omitempty"`
	// +optional
	MaxImportRemoteFileSize int64 `json:"maxImportRemoteFileSize,omitempty"`
	// +optional
	MaxImportSize int64 `json:"maxImportSize,omitempty"`
	// +optional
	MaxLoginAttempts int64 `json:"maxLoginAttempts,omitempty"`
	// +optional
	MaxNumberOfRepositoryDownloads int64 `json:"maxNumberOfRepositoryDownloads,omitempty"`
	// +optional
	MaxNumberOfRepositoryDownloadsWithinTimePeriod int64 `json:"maxNumberOfRepositoryDownloadsWithinTimePeriod,omitempty"`
	// +optional
	MaxPagesSize int64 `json:"maxPagesSize,omitempty"`
	// +optional
	MaxPersonalAccessTokenLifetime int64 `json:"maxPersonalAccessTokenLifetime,omitempty"`
	// +optional
	MaxSSHKeyLifetime int64 `json:"maxSshKeyLifetime,omitempty"`
	// +optional
	MaxTerraformStateSizeBytes int64 `json:"maxTerraformStateSizeBytes,omitempty"`
	// +optional
	MaxYAMLDepth int64 `json:"maxYamlDepth,omitempty"`
	// +optional
	MaxYAMLSizeBytes int64 `json:"maxYamlSizeBytes,omitempty"`
	// +optional
	MetricsMethodCallThreshold int64 `json:"metricsMethodCallThreshold,omitempty"`
	// +optional
	MinimumPasswordLength int64 `json:"minimumPasswordLength,omitempty"`
	// +optional
	MirrorAvailable bool `json:"mirrorAvailable,omitempty"`
	// +optional
	MirrorCapacityThreshold int64 `json:"mirrorCapacityThreshold,omitempty"`
	// +optional
	MirrorMaxCapacity int64 `json:"mirrorMaxCapacity,omitempty"`
	// +optional
	MirrorMaxDelay int64 `json:"mirrorMaxDelay,omitempty"`
	// +optional
	NPMPackageRequestsForwarding bool `json:"npmPackageRequestsForwarding,omitempty"`
	// +optional
	NotesCreateLimit int64 `json:"notesCreateLimit,omitempty"`
	// +optional
	NotifyOnUnknownSignIn bool `json:"notifyOnUnknownSignIn,omitempty"`
	// +optional
	NugetSkipMetadataURLValidation bool `json:"nugetSkipMetadataUrlValidation,omitempty"`
	// +optional
	OutboundLocalRequestsAllowlistRaw string `json:"outboundLocalRequestsAllowlistRaw,omitempty"`
	// +optional
	OutboundLocalRequestsWhitelist []string `json:"outboundLocalRequestsWhitelist,omitempty"`
	// +optional
	PackageMetadataPURLTypes []int64 `json:"packageMetadataPUrlTypes,omitempty"`
	// +optional
	PackageRegistryAllowAnyoneToPullOption bool `json:"packageRegistryAllowAnyoneToPullOption,omitempty"`
	// +optional
	PackageRegistryCleanupPoliciesWorkerCapacity int64 `json:"packageRegistryCleanupPoliciesWorkerCapacity,omitempty"`
	// +optional
	PagesDomainVerificationEnabled bool `json:"pagesDomainVerificationEnabled,omitempty"`
	// +optional
	PasswordAuthenticationEnabledForGit bool `json:"passwordAuthenticationEnabledForGit,omitempty"`
	// +optional
	PasswordAuthenticationEnabledForWeb bool `json:"passwordAuthenticationEnabledForWeb,omitempty"`
	// +optional
	PasswordNumberRequired bool `json:"passwordNumberRequired,omitempty"`
	// +optional
	PasswordSymbolRequired bool `json:"passwordSymbolRequired,omitempty"`
	// +optional
	PasswordUppercaseRequired bool `json:"passwordUppercaseRequired,omitempty"`
	// +optional
	PasswordLowercaseRequired bool `json:"passwordLowercaseRequired,omitempty"`
	// +optional
	PerformanceBarAllowedGroupPath string `json:"performanceBarAllowedGroupPath,omitempty"`
	// +optional
	PersonalAccessTokenPrefix string `json:"personalAccessTokenPrefix,omitempty"`
	// +optional
	PipelineLimitPerProjectUserSha int64 `json:"pipelineLimitPerProjectUserSha,omitempty"`
	// +optional
	PlantumlEnabled bool `json:"plantumlEnabled,omitempty"`
	// +optional
	PlantumlURL string `json:"plantumlUrl,omitempty"`
	// +optional
	PollingIntervalMultiplier float64 `json:"pollingIntervalMultiplier,omitempty"`
	// +optional
	PreventMergeRequestsAuthorApproval bool `json:"preventMergeRequestsAuthorApproval,omitempty"`
	// +optional
	PreventMergeRequestsCommittersApproval bool `json:"preventMergeRequestsCommittersApproval,omitempty"`
	// +optional
	ProjectDownloadExportLimit int64 `json:"projectDownloadExportLimit,omitempty"`
	// +optional
	ProjectExportEnabled bool `json:"projectExportEnabled,omitempty"`
	// +optional
	ProjectExportLimit int64 `json:"projectExportLimit,omitempty"`
	// +optional
	ProjectImportLimit int64 `json:"projectImportLimit,omitempty"`
	// +optional
	ProjectJobsAPIRateLimit int64 `json:"projectJobsApiRateLimit,omitempty"`
	// +optional
	ProjectRunnerTokenExpirationInterval int64 `json:"projectRunnerTokenExpirationInterval,omitempty"`
	// +optional
	ProjectsAPIRateLimitUnauthenticated int64 `json:"projectsApiRateLimitUnauthenticated,omitempty"`
	// +optional
	PrometheusMetricsEnabled bool `json:"prometheusMetricsEnabled,omitempty"`
	// +optional
	ProtectedCIVariables bool `json:"protectedCIVariables,omitempty"`
	// +optional
	PseudonymizerEnabled bool `json:"pseudonymizerEnabled,omitempty"`
	// +optional
	PushEventActivitiesLimit int64 `json:"pushEventActivitiesLimit,omitempty"`
	// +optional
	PushEventHooksLimit int64 `json:"pushEventHooksLimit,omitempty"`
	// +optional
	PyPIPackageRequestsForwarding bool `json:"pyPIpackageRequestsForwarding,omitempty"`
	// +optional
	RSAKeyRestriction int64 `json:"rsaKeyRestriction,omitempty"`
	// +optional
	RateLimitingResponseText string `json:"rateLimitingResponseText,omitempty"`
	// +optional
	RawBlobRequestLimit int64 `json:"rawBlobRequestLimit,omitempty"`
	// +optional
	RecaptchaEnabled bool `json:"recaptchaEnabled,omitempty"`
	// +optional
	ReceiveMaxInputSize int64 `json:"receiveMaxInputSize,omitempty"`
	// +optional
	ReceptiveClusterAgentsEnabled bool `json:"receptiveClusterAgentsEnabled,omitempty"`
	// +optional
	RememberMeEnabled bool `json:"rememberMeEnabled,omitempty"`
	// +optional
	RepositoryChecksEnabled bool `json:"repositoryChecksEnabled,omitempty"`
	// +optional
	RepositorySizeLimit int64 `json:"repositorySizeLimit,omitempty"`
	// +optional
	RepositoryStorages []string `json:"repositoryStorages,omitempty"`
	// +optional
	RepositoryStoragesWeighted map[string]int64 `json:"repositoryStoragesWeighted,omitempty"`
	// +optional
	RequireAdminApprovalAfterUserSignup bool `json:"requireAdminApprovalAfterUserSignup,omitempty"`
	// +optional
	RequireAdminTwoFactorAuthentication bool `json:"requireAdminTwoFactorAuthentication,omitempty"`
	// +optional
	RequirePersonalAccessTokenExpiry bool `json:"requirePersonalAccessTokenExpiry,omitempty"`
	// +optional
	RequireTwoFactorAuthentication bool `json:"requireTwoFactorAuthentication,omitempty"`
	// +optional
	RestrictedVisibilityLevels []string `json:"restrictedVisibilityLevels,omitempty"`
	// +optional
	RunnerTokenExpirationInterval int64 `json:"runnerTokenExpirationInterval,omitempty"`
	// +optional
	SearchRateLimit int64 `json:"searchRateLimit,omitempty"`
	// +optional
	SearchRateLimitUnauthenticated int64 `json:"searchRateLimitUnauthenticated,omitempty"`
	// +optional
	SecretDetectionRevocationTokenTypesURL string `json:"secretDetectionRevocationTokenTypesUrl,omitempty"`
	// +optional
	SecretDetectionTokenRevocationEnabled bool `json:"secretDetectionTokenRevocationEnabled,omitempty"`
	// +optional
	SecretDetectionTokenRevocationURL string `json:"secretDetectionTokenRevocationUrl,omitempty"`
	// +optional
	SecurityApprovalPoliciesLimit int64 `json:"securityApprovalPoliciesLimit,omitempty"`
	// +optional
	SecurityPolicyGlobalGroupApproversEnabled bool `json:"securityPolicyGlobalGroupApproversEnabled,omitempty"`
	// +optional
	SecurityTXTContent string `json:"securityTXTContent,omitempty"`
	// +optional
	SendUserConfirmationEmail bool `json:"sendUserConfirmationEmail,omitempty"`
	// +optional
	SentryClientsideDSN string `json:"sentryClientsideDSN,omitempty"`
	// +optional
	SentryDSN string `json:"sentryDSN,omitempty"`
	// +optional
	SentryEnabled bool `json:"sentryEnabled,omitempty"`
	// +optional
	SentryEnvironment string `json:"sentryEnvironment,omitempty"`
	// +optional
	ServiceAccessTokensExpirationEnforced bool `json:"serviceAccessTokensExpirationEnforced,omitempty"`
	// +optional
	SessionExpireDelay int64 `json:"sessionExpireDelay,omitempty"`
	// +optional
	SharedRunnersEnabled bool `json:"sharedRunnersEnabled,omitempty"`
	// +optional
	SharedRunnersMinutes int64 `json:"sharedRunnersMinutes,omitempty"`
	// +optional
	SharedRunnersText string `json:"sharedRunnersText,omitempty"`
	// +optional
	SidekiqJobLimiterCompressionThresholdBytes int64 `json:"sidekiqJobLimiterCompressionThresholdBytes,omitempty"`
	// +optional
	SidekiqJobLimiterLimitBytes int64 `json:"sidekiqJobLimiterLimitBytes,omitempty"`
	// +optional
	SidekiqJobLimiterMode string `json:"sidekiqJobLimiterMode,omitempty"`
	// +optional
	SignInText string `json:"signInText,omitempty"`
	// +optional
	SignupEnabled bool `json:"signupEnabled,omitempty"`
	// +optional
	SilentAdminExportsEnabled bool `json:"silentAdminExportsEnabled,omitempty"`
	// +optional
	SilentModeEnabled bool `json:"silentModeEnabled,omitempty"`
	// +optional
	SlackAppEnabled bool `json:"slackAppEnabled,omitempty"`
	// +optional
	SlackAppID string `json:"slackAppId,omitempty"`
	// +optional
	SnippetSizeLimit int64 `json:"snippetSizeLimit,omitempty"`
	// +optional
	SnowplowAppID string `json:"snowplowAppId,omitempty"`
	// +optional
	SnowplowCollectorHostname string `json:"snowplowCollectorHostname,omitempty"`
	// +optional
	SnowplowCookieDomain string `json:"snowplowCookieDomain,omitempty"`
	// +optional
	SnowplowDatabaseCollectorHostname string `json:"snowplowDatabaseCollectorHostname,omitempty"`
	// +optional
	SnowplowEnabled bool `json:"snowplowEnabled,omitempty"`
	// +optional
	SourcegraphEnabled bool `json:"sourcegraphEnabled,omitempty"`
	// +optional
	SourcegraphPublicOnly bool `json:"sourcegraphPublicOnly,omitempty"`
	// +optional
	SourcegraphURL string `json:"sourcegraphUrl,omitempty"`
	// +optional
	SpamCheckEndpointEnabled bool `json:"spamCheckEndpointEnabled,omitempty"`
	// +optional
	SpamCheckEndpointURL string `json:"spamCheckEndpointUrl,omitempty"`
	// +optional
	StaticObjectsExternalStorageURL string `json:"staticObjectsExternalStorageUrl,omitempty"`
	// +optional
	SuggestPipelineEnabled bool `json:"suggestPipelineEnabled,omitempty"`
	// +optional
	TerminalMaxSessionTime int64 `json:"terminalMaxSessionTime,omitempty"`
	// +optional
	Terms string `json:"terms,omitempty"`
	// +optional
	ThrottleAuthenticatedAPIEnabled bool `json:"throttleAuthenticatedApiEnabled,omitempty"`
	// +optional
	ThrottleAuthenticatedAPIPeriodInSeconds int64 `json:"throttleAuthenticatedApiPeriodInSeconds,omitempty"`
	// +optional
	ThrottleAuthenticatedAPIRequestsPerPeriod int64 `json:"throttleAuthenticatedApiRequestsPerPeriod,omitempty"`
	// +optional
	ThrottleAuthenticatedDeprecatedAPIEnabled bool `json:"throttleAuthenticatedDeprecatedApiEnabled,omitempty"`
	// +optional
	ThrottleAuthenticatedDeprecatedAPIPeriodInSeconds int64 `json:"throttleAuthenticatedDeprecatedApiPeriodInSeconds,omitempty"`
	// +optional
	ThrottleAuthenticatedDeprecatedAPIRequestsPerPeriod int64 `json:"throttleAuthenticatedDeprecatedApiRequestsPerPeriod,omitempty"`
	// +optional
	ThrottleAuthenticatedFilesAPIEnabled bool `json:"throttleAuthenticatedFilesApiEnabled,omitempty"`
	// +optional
	ThrottleAuthenticatedFilesAPIPeriodInSeconds int64 `json:"throttleAuthenticatedFilesApiPeriodInSeconds,omitempty"`
	// +optional
	ThrottleAuthenticatedFilesAPIRequestsPerPeriod int64 `json:"throttleAuthenticatedFilesApiRequestsPerPeriod,omitempty"`
	// +optional
	ThrottleAuthenticatedGitLFSEnabled bool `json:"throttleAuthenticatedGitLFSEnabled,omitempty"`
	// +optional
	ThrottleAuthenticatedGitLFSPeriodInSeconds int64 `json:"throttleAuthenticatedGitLFSPeriodInSeconds,omitempty"`
	// +optional
	ThrottleAuthenticatedGitLFSRequestsPerPeriod int64 `json:"throttleAuthenticatedGitLFSRequestsPerPeriod,omitempty"`
	// +optional
	ThrottleAuthenticatedPackagesAPIEnabled bool `json:"throttleAuthenticatedPackagesApiEnabled,omitempty"`
	// +optional
	ThrottleAuthenticatedPackagesAPIPeriodInSeconds int64 `json:"throttleAuthenticatedPackagesApiPeriodInSeconds,omitempty"`
	// +optional
	ThrottleAuthenticatedPackagesAPIRequestsPerPeriod int64 `json:"throttleAuthenticatedPackagesApiRequestsPerPeriod,omitempty"`
	// +optional
	ThrottleAuthenticatedWebEnabled bool `json:"throttleAuthenticatedWebEnabled,omitempty"`
	// +optional
	ThrottleAuthenticatedWebPeriodInSeconds int64 `json:"throttleAuthenticatedWebPeriodInSeconds,omitempty"`
	// +optional
	ThrottleAuthenticatedWebRequestsPerPeriod int64 `json:"throttleAuthenticatedWebRequestsPerPeriod,omitempty"`
	// +optional
	ThrottleIncidentManagementNotificationEnabled bool `json:"throttleIncidentManagementNotificationEnabled,omitempty"`
	// +optional
	ThrottleIncidentManagementNotificationPerPeriod int64 `json:"throttleIncidentManagementNotificationPerPeriod,omitempty"`
	// +optional
	ThrottleIncidentManagementNotificationPeriodInSeconds int64 `json:"throttleIncidentManagementNotificationPeriodInSeconds,omitempty"`
	// +optional
	ThrottleProtectedPathsEnabled bool `json:"throttleProtectedPathsEnabled,omitempty"`
	// +optional
	ThrottleProtectedPathsPeriodInSeconds int64 `json:"throttleProtectedPathsPeriodInSeconds,omitempty"`
	// +optional
	ThrottleProtectedPathsRequestsPerPeriod int64 `json:"throttleProtectedPathsRequestsPerPeriod,omitempty"`
	// +optional
	ThrottleUnauthenticatedAPIEnabled bool `json:"throttleUnauthenticatedApiEnabled,omitempty"`
	// +optional
	ThrottleUnauthenticatedAPIPeriodInSeconds int64 `json:"throttleUnauthenticatedApiPeriodInSeconds,omitempty"`
	// +optional
	ThrottleUnauthenticatedAPIRequestsPerPeriod int64 `json:"throttleUnauthenticatedApiRequestsPerPeriod,omitempty"`
	// +optional
	ThrottleUnauthenticatedDeprecatedAPIEnabled bool `json:"throttleUnauthenticatedDeprecatedApiEnabled,omitempty"`
	// +optional
	ThrottleUnauthenticatedDeprecatedAPIPeriodInSeconds int64 `json:"throttleUnauthenticatedDeprecatedApiPeriodInSeconds,omitempty"`
	// +optional
	ThrottleUnauthenticatedDeprecatedAPIRequestsPerPeriod int64 `json:"throttleUnauthenticatedDeprecatedApiRequestsPerPeriod,omitempty"`
	// +optional
	ThrottleUnauthenticatedFilesAPIEnabled bool `json:"throttleUnauthenticatedFilesApiEnabled,omitempty"`
	// +optional
	ThrottleUnauthenticatedFilesAPIPeriodInSeconds int64 `json:"throttleUnauthenticatedFilesApiPeriodInSeconds,omitempty"`
	// +optional
	ThrottleUnauthenticatedFilesAPIRequestsPerPeriod int64 `json:"throttleUnauthenticatedFilesApiRequestsPerPeriod,omitempty"`
	// +optional
	ThrottleUnauthenticatedGitLFSEnabled bool `json:"throttleUnauthenticatedGitLFSEnabled,omitempty"`
	// +optional
	ThrottleUnauthenticatedGitLFSPeriodInSeconds int64 `json:"throttleUnauthenticatedGitLFSPeriodInSeconds,omitempty"`
	// +optional
	ThrottleUnauthenticatedGitLFSRequestsPerPeriod int64 `json:"throttleUnauthenticatedGitLFSRequestsPerPeriod,omitempty"`
	// +optional
	ThrottleUnauthenticatedPackagesAPIEnabled bool `json:"throttleUnauthenticatedPackagesApiEnabled,omitempty"`
	// +optional
	ThrottleUnauthenticatedPackagesAPIPeriodInSeconds int64 `json:"throttleUnauthenticatedPackagesApiPeriodInSeconds,omitempty"`
	// +optional
	ThrottleUnauthenticatedPackagesAPIRequestsPerPeriod int64 `json:"throttleUnauthenticatedPackagesApiRequestsPerPeriod,omitempty"`
	// +optional
	ThrottleUnauthenticatedWebEnabled bool `json:"throttleUnauthenticatedWebEnabled,omitempty"`
	// +optional
	ThrottleUnauthenticatedWebPeriodInSeconds int64 `json:"throttleUnauthenticatedWebPeriodInSeconds,omitempty"`
	// +optional
	ThrottleUnauthenticatedWebRequestsPerPeriod int64 `json:"throttleUnauthenticatedWebRequestsPerPeriod,omitempty"`
	// +optional
	TimeTrackingLimitToHours bool `json:"timeTrackingLimitToHours,omitempty"`
	// +optional
	TwoFactorGracePeriod int64 `json:"twoFactorGracePeriod,omitempty"`
	// +optional
	UnconfirmedUsersDeleteAfterDays int64 `json:"unconfirmedUsersDeleteAfterDays,omitempty"`
	// +optional
	UniqueIPsLimitEnabled bool `json:"uniqueIpsLimitEnabled,omitempty"`
	// +optional
	UniqueIPsLimitPerUser int64 `json:"uniqueIpsLimitPerUser,omitempty"`
	// +optional
	UniqueIPsLimitTimeWindow int64 `json:"uniqueIpsLimitTimeWindow,omitempty"`
	// +optional
	UpdateRunnerVersionsEnabled bool `json:"updateRunnerVersionsEnabled,omitempty"`
	// +optional
	UpdatedAt *metav1.Time `json:"updatedAt,omitempty"`
	// +optional
	UpdatingNameDisabledForUsers bool `json:"updatingNameDisabledForUsers,omitempty"`
	// +optional
	UsagePingEnabled bool `json:"usagePingEnabled,omitempty"`
	// +optional
	UsagePingFeaturesEnabled bool `json:"usagePingFeaturesEnabled,omitempty"`
	// +optional
	UseClickhouseForAnalytics bool `json:"useClickhouseForAnalytics,omitempty"`
	// +optional
	UserDeactivationEmailsEnabled bool `json:"userDeactivationEmailsEnabled,omitempty"`
	// +optional
	UserDefaultExternal bool `json:"userDefaultExternal,omitempty"`
	// +optional
	UserDefaultInternalRegex string `json:"userDefaultInternalRegex,omitempty"`
	// +optional
	UserDefaultsToPrivateProfile bool `json:"userDefaultsToPrivateProfile,omitempty"`
	// +optional
	UserOauthApplications bool `json:"userOauthApplications,omitempty"`
	// +optional
	UserShowAddSSHKeyMessage bool `json:"userShowAddSshKeyMessage,omitempty"`
	// +optional
	UsersGetByIDLimit int64 `json:"usersGetByIdLimit,omitempty"`
	// +optional
	UsersGetByIDLimitAllowlistRaw string `json:"usersGetByIdLimitAllowlistRaw,omitempty"`
	// +optional
	ValidRunnerRegistrars []string `json:"validRunnerRegistrars,omitempty"`
	// +optional
	VersionCheckEnabled bool `json:"versionCheckEnabled,omitempty"`
	// +optional
	WebIDEClientsidePreviewEnabled bool `json:"webIdEClientsidePreviewEnabled,omitempty"`
	// +optional
	WhatsNewVariant string `json:"whatsNewVariant,omitempty"`
	// +optional
	WikiPageMaxContentBytes int64 `json:"wikiPageMaxContentBytes,omitempty"`
	// +optional
	DefaultBranchProtection int64 `json:"defaultBranchProtection,omitempty"`
	// +optional
	HousekeepingBitmapsEnabled bool `json:"housekeepingBitmapsEnabled,omitempty"`
	// +optional
	HousekeepingFullRepackPeriod int64 `json:"housekeepingFullRepackPeriod,omitempty"`
	// +optional
	HousekeepingGcPeriod int64 `json:"housekeepingGcPeriod,omitempty"`
	// +optional
	HousekeepingIncrementalRepackPeriod int64 `json:"housekeepingIncrementalRepackPeriod,omitempty"`
	// +optional
	PerformanceBarAllowedGroupID int64 `json:"performanceBarAllowedGroupId,omitempty"`
	// +optional
	PerformanceBarEnabled bool `json:"performanceBarEnabled,omitempty"`
	// +optional
	AdminNotificationEmail string `json:"adminNotificationEmail,omitempty"`
	// +optional
	AllowLocalRequestsFromHooksAndServices bool `json:"allowLocalRequestsFromHooksAndServices,omitempty"`
	// +optional
	AssetProxyWhitelist []string `json:"assetProxyWhitelist,omitempty"`
	// +optional
	ThrottleUnauthenticatedEnabled bool `json:"throttleUnauthenticatedEnabled,omitempty"`
	// +optional
	ThrottleUnauthenticatedPeriodInSeconds int64 `json:"throttleUnauthenticatedPeriodInSeconds,omitempty"`
	// +optional
	ThrottleUnauthenticatedRequestsPerPeriod int64 `json:"throttleUnauthenticatedRequestsPerPeriod,omitempty"`
	// +optional
	UserEmailLookupLimit int64 `json:"userEmailLookupLimit,omitempty"`
}

