/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by generate.go. DO NOT EDIT.

// Code generated by hack/generate-cluster-scope.go - DO NOT EDIT.

package settings

import (
	"context"

	"github.com/crossplane-contrib/provider-gitlab/apis/cluster/instance/v1alpha1"
	"github.com/crossplane/crossplane-runtime/v2/pkg/errors"
	"github.com/crossplane/crossplane-runtime/v2/pkg/resource"

	"github.com/crossplane-contrib/provider-gitlab/pkg/cluster/controller/common"
)

func (e *external) updateSettingsFromSecrets(mg resource.Managed, ctx context.Context, params *v1alpha1.ApplicationSettingsParameters) error {
	if params.AkismetAPIKeySecretRef != nil {
		if err := common.UpdateStringFromSecret(mg, ctx, e.kube, params.AkismetAPIKeySecretRef, &params.AkismetAPIKey); err != nil {
			return errors.Wrap(err, "failed to get AkismetAPIKey from secret reference")
		}
	}

	if params.AssetProxySecretKeySecretRef != nil {
		if err := common.UpdateStringFromSecret(mg, ctx, e.kube, params.AssetProxySecretKeySecretRef, &params.AssetProxySecretKey); err != nil {
			return errors.Wrap(err, "failed to get AssetProxySecretKey from secret reference")
		}
	}

	if params.EKSAccessKeyIDSecretRef != nil {
		if err := common.UpdateStringFromSecret(mg, ctx, e.kube, params.EKSAccessKeyIDSecretRef, &params.EKSAccessKeyID); err != nil {
			return errors.Wrap(err, "failed to get EKSAccessKeyID from secret reference")
		}
	}

	if params.EKSSecretAccessKeySecretRef != nil {
		if err := common.UpdateStringFromSecret(mg, ctx, e.kube, params.EKSSecretAccessKeySecretRef, &params.EKSSecretAccessKey); err != nil {
			return errors.Wrap(err, "failed to get EKSSecretAccessKey from secret reference")
		}
	}

	if params.ElasticsearchAWSAccessKeySecretRef != nil {
		if err := common.UpdateStringFromSecret(mg, ctx, e.kube, params.ElasticsearchAWSAccessKeySecretRef, &params.ElasticsearchAWSAccessKey); err != nil {
			return errors.Wrap(err, "failed to get ElasticsearchAWSAccessKey from secret reference")
		}
	}

	if params.ElasticsearchAWSSecretAccessKeySecretRef != nil {
		if err := common.UpdateStringFromSecret(mg, ctx, e.kube, params.ElasticsearchAWSSecretAccessKeySecretRef, &params.ElasticsearchAWSSecretAccessKey); err != nil {
			return errors.Wrap(err, "failed to get ElasticsearchAWSSecretAccessKey from secret reference")
		}
	}

	if params.ElasticsearchPasswordSecretRef != nil {
		if err := common.UpdateStringFromSecret(mg, ctx, e.kube, params.ElasticsearchPasswordSecretRef, &params.ElasticsearchPassword); err != nil {
			return errors.Wrap(err, "failed to get ElasticsearchPassword from secret reference")
		}
	}

	if params.ExternalAuthClientKeySecretRef != nil {
		if err := common.UpdateStringFromSecret(mg, ctx, e.kube, params.ExternalAuthClientKeySecretRef, &params.ExternalAuthClientKey); err != nil {
			return errors.Wrap(err, "failed to get ExternalAuthClientKey from secret reference")
		}
	}

	if params.ExternalPipelineValidationServiceTokenSecretRef != nil {
		if err := common.UpdateStringFromSecret(mg, ctx, e.kube, params.ExternalPipelineValidationServiceTokenSecretRef, &params.ExternalPipelineValidationServiceToken); err != nil {
			return errors.Wrap(err, "failed to get ExternalPipelineValidationServiceToken from secret reference")
		}
	}

	if params.JiraConnectApplicationKeySecretRef != nil {
		if err := common.UpdateStringFromSecret(mg, ctx, e.kube, params.JiraConnectApplicationKeySecretRef, &params.JiraConnectApplicationKey); err != nil {
			return errors.Wrap(err, "failed to get JiraConnectApplicationKey from secret reference")
		}
	}

	if params.MailgunSigningKeySecretRef != nil {
		if err := common.UpdateStringFromSecret(mg, ctx, e.kube, params.MailgunSigningKeySecretRef, &params.MailgunSigningKey); err != nil {
			return errors.Wrap(err, "failed to get MailgunSigningKey from secret reference")
		}
	}

	if params.RecaptchaPrivateKeySecretRef != nil {
		if err := common.UpdateStringFromSecret(mg, ctx, e.kube, params.RecaptchaPrivateKeySecretRef, &params.RecaptchaPrivateKey); err != nil {
			return errors.Wrap(err, "failed to get RecaptchaPrivateKey from secret reference")
		}
	}

	if params.RecaptchaSiteKeySecretRef != nil {
		if err := common.UpdateStringFromSecret(mg, ctx, e.kube, params.RecaptchaSiteKeySecretRef, &params.RecaptchaSiteKey); err != nil {
			return errors.Wrap(err, "failed to get RecaptchaSiteKey from secret reference")
		}
	}

	if params.SecretDetectionTokenRevocationTokenSecretRef != nil {
		if err := common.UpdateStringFromSecret(mg, ctx, e.kube, params.SecretDetectionTokenRevocationTokenSecretRef, &params.SecretDetectionTokenRevocationToken); err != nil {
			return errors.Wrap(err, "failed to get SecretDetectionTokenRevocationToken from secret reference")
		}
	}

	if params.SlackAppSecretSecretRef != nil {
		if err := common.UpdateStringFromSecret(mg, ctx, e.kube, params.SlackAppSecretSecretRef, &params.SlackAppSecret); err != nil {
			return errors.Wrap(err, "failed to get SlackAppSecret from secret reference")
		}
	}

	if params.SlackAppSigningSecretSecretRef != nil {
		if err := common.UpdateStringFromSecret(mg, ctx, e.kube, params.SlackAppSigningSecretSecretRef, &params.SlackAppSigningSecret); err != nil {
			return errors.Wrap(err, "failed to get SlackAppSigningSecret from secret reference")
		}
	}

	if params.SlackAppVerificationTokenSecretRef != nil {
		if err := common.UpdateStringFromSecret(mg, ctx, e.kube, params.SlackAppVerificationTokenSecretRef, &params.SlackAppVerificationToken); err != nil {
			return errors.Wrap(err, "failed to get SlackAppVerificationToken from secret reference")
		}
	}

	if params.SpamCheckAPIKeySecretRef != nil {
		if err := common.UpdateStringFromSecret(mg, ctx, e.kube, params.SpamCheckAPIKeySecretRef, &params.SpamCheckAPIKey); err != nil {
			return errors.Wrap(err, "failed to get SpamCheckAPIKey from secret reference")
		}
	}

	if params.StaticObjectsExternalStorageAuthTokenSecretRef != nil {
		if err := common.UpdateStringFromSecret(mg, ctx, e.kube, params.StaticObjectsExternalStorageAuthTokenSecretRef, &params.StaticObjectsExternalStorageAuthToken); err != nil {
			return errors.Wrap(err, "failed to get StaticObjectsExternalStorageAuthToken from secret reference")
		}
	}

	return nil
}
