/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by hack/generate-cluster-scope.go - DO NOT EDIT.

package applications

import (
	"context"
	"net/http"
	"testing"
	"time"

	"github.com/crossplane/crossplane-runtime/v2/pkg/errors"
	"github.com/crossplane/crossplane-runtime/v2/pkg/meta"
	"github.com/crossplane/crossplane-runtime/v2/pkg/reconciler/managed"
	"github.com/crossplane/crossplane-runtime/v2/pkg/resource"
	"github.com/crossplane/crossplane-runtime/v2/pkg/test"
	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
	"github.com/google/go-cmp/cmp"
	pkgerrors "github.com/pkg/errors"
	gitlab "gitlab.com/gitlab-org/api/client-go/v2"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/utils/ptr"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/crossplane-contrib/provider-gitlab/apis/cluster/instance/v1alpha1"
	instanceclient "github.com/crossplane-contrib/provider-gitlab/pkg/cluster/clients/instance"
)

var (
	unexpectedItem resource.Managed
	errBoom        = errors.New("boom")
)

const (
	testAppName        = "test-app"
	testRedirectURI    = "https://example.com/callback"
	testApplicationID  = "abc123clientid"
	testSecret         = "supersecret"
	testExternalNameID = "42"
)

// MockApplicationClient is a mock implementation of instance.ApplicationClient.
type MockApplicationClient struct {
	MockCreateApplication      func(opt *gitlab.CreateApplicationOptions, options ...gitlab.RequestOptionFunc) (*gitlab.Application, *gitlab.Response, error)
	MockListApplications       func(opt *gitlab.ListApplicationsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Application, *gitlab.Response, error)
	MockDeleteApplication      func(application int64, options ...gitlab.RequestOptionFunc) (*gitlab.Response, error)
	MockRenewApplicationSecret func(application int64, options ...gitlab.RequestOptionFunc) (*gitlab.Application, *gitlab.Response, error)
}

func (m *MockApplicationClient) CreateApplication(opt *gitlab.CreateApplicationOptions, options ...gitlab.RequestOptionFunc) (*gitlab.Application, *gitlab.Response, error) {
	return m.MockCreateApplication(opt, options...)
}

func (m *MockApplicationClient) ListApplications(opt *gitlab.ListApplicationsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Application, *gitlab.Response, error) {
	return m.MockListApplications(opt, options...)
}

func (m *MockApplicationClient) DeleteApplication(application int64, options ...gitlab.RequestOptionFunc) (*gitlab.Response, error) {
	return m.MockDeleteApplication(application, options...)
}

func (m *MockApplicationClient) RenewApplicationSecret(application int64, options ...gitlab.RequestOptionFunc) (*gitlab.Application, *gitlab.Response, error) {
	return m.MockRenewApplicationSecret(application, options...)
}

type args struct {
	client instanceclient.ApplicationClient
	kube   client.Client
	cr     resource.Managed
}

type applicationModifier func(*v1alpha1.Application)

func withExternalName(n string) applicationModifier {
	return func(r *v1alpha1.Application) { meta.SetExternalName(r, n) }
}

func withSpec(p v1alpha1.ApplicationParameters) applicationModifier {
	return func(r *v1alpha1.Application) { r.Spec.ForProvider = p }
}

func withConditions(c ...v2.Condition) applicationModifier {
	return func(r *v1alpha1.Application) { r.Status.SetConditions(c...) }
}

func withAtProvider(o v1alpha1.ApplicationObservation) applicationModifier {
	return func(r *v1alpha1.Application) { r.Status.AtProvider = o }
}

func withConnectionSecretRef(name string) applicationModifier {
	return func(r *v1alpha1.Application) {
		r.Spec.WriteConnectionSecretToReference = &v2.SecretReference{Name: name}
	}
}

func withNextRenewalAtStr(s string) applicationModifier {
	return func(r *v1alpha1.Application) {
		t, _ := time.Parse(time.RFC3339, s)
		mt := metav1.NewTime(t)
		r.Status.AtProvider.NextRenewalAt = &mt
	}
}

func withAnnotations(a map[string]string) applicationModifier {
	return func(r *v1alpha1.Application) {
		existing := r.GetAnnotations()
		if existing == nil {
			existing = map[string]string{}
		}
		for k, v := range a {
			existing[k] = v
		}
		r.SetAnnotations(existing)
	}
}

func application(m ...applicationModifier) *v1alpha1.Application {
	cr := &v1alpha1.Application{}
	for _, f := range m {
		f(cr)
	}
	return cr
}

func bPtr(b bool) *bool { return &b }

var testApp = &gitlab.Application{
	ID:              42,
	ApplicationID:   testApplicationID,
	ApplicationName: testAppName,
	Secret:          testSecret,
	CallbackURL:     testRedirectURI,
	Confidential:    false,
	Scopes:          []string{"api", "read_user"},
}

var testDesiredSpec = v1alpha1.ApplicationParameters{
	Name:        testAppName,
	RedirectURI: testRedirectURI,
	Scopes:      []string{"api", "read_user"},
}

func TestConnect(t *testing.T) {
	type want struct {
		err error
	}

	cases := map[string]struct {
		args args
		want want
	}{
		"InvalidInput": {
			args: args{cr: unexpectedItem},
			want: want{err: errors.New(errNotApplication)},
		},
		"ProviderConfigRefNotGivenError": {
			args: args{cr: application(), kube: &test.MockClient{MockGet: test.NewMockGetFn(nil)}},
			want: want{err: pkgerrors.New("providerConfigRef is not given")},
		},
	}

	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			c := &connector{kube: tc.args.kube, newGitlabClientFn: nil}
			got, err := c.Connect(context.Background(), tc.args.cr)
			if diff := cmp.Diff(tc.want.err, err, test.EquateErrors()); diff != "" {
				t.Errorf("Connect(): -want, +got:\n%s", diff)
			}
			_ = got
		})
	}
}

func TestObserve(t *testing.T) {
	pastDate := time.Now().UTC().Add(-24 * time.Hour).Format(time.RFC3339)
	futureDate := time.Now().UTC().Add(24 * time.Hour).Format(time.RFC3339)

	type want struct {
		cr     resource.Managed
		result managed.ExternalObservation
		err    error
	}

	cases := map[string]struct {
		args args
		want want
	}{
		"InvalidInput": {
			args: args{cr: unexpectedItem},
			want: want{cr: unexpectedItem, err: errors.New(errNotApplication)},
		},
		"NoExternalName": {
			args: args{cr: application(withSpec(testDesiredSpec))},
			want: want{
				cr:     application(withSpec(testDesiredSpec)),
				result: managed.ExternalObservation{ResourceExists: false},
			},
		},
		"NonIntegerExternalName": {
			args: args{
				client: &MockApplicationClient{
					MockListApplications: func(opt *gitlab.ListApplicationsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Application, *gitlab.Response, error) {
						return []*gitlab.Application{}, &gitlab.Response{Response: &http.Response{StatusCode: 200}}, nil
					},
				},
				cr: application(withExternalName("not-an-int"), withSpec(testDesiredSpec)),
			},
			want: want{
				cr:  application(withExternalName("not-an-int"), withSpec(testDesiredSpec)),
				err: errors.New(errIDNotInt),
			},
		},
		"ListError": {
			args: args{
				client: &MockApplicationClient{
					MockListApplications: func(opt *gitlab.ListApplicationsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Application, *gitlab.Response, error) {
						return nil, &gitlab.Response{Response: &http.Response{StatusCode: 500}}, errBoom
					},
				},
				cr: application(withExternalName(testExternalNameID), withSpec(testDesiredSpec)),
			},
			want: want{
				cr:  application(withExternalName(testExternalNameID), withSpec(testDesiredSpec)),
				err: errors.Wrap(errBoom, errGetFailed),
			},
		},
		"ListError404": {
			args: args{
				client: &MockApplicationClient{
					MockListApplications: func(opt *gitlab.ListApplicationsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Application, *gitlab.Response, error) {
						return nil, &gitlab.Response{Response: &http.Response{StatusCode: 404}}, errBoom
					},
				},
				cr: application(withExternalName(testExternalNameID), withSpec(testDesiredSpec)),
			},
			want: want{
				cr:  application(withExternalName(testExternalNameID), withSpec(testDesiredSpec)),
				err: errors.Wrap(errBoom, errGetFailed),
			},
		},
		"NotFoundSinglePage": {
			args: args{
				client: &MockApplicationClient{
					MockListApplications: func(opt *gitlab.ListApplicationsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Application, *gitlab.Response, error) {
						return []*gitlab.Application{}, &gitlab.Response{Response: &http.Response{StatusCode: 200}}, nil
					},
				},
				cr: application(withExternalName(testExternalNameID), withSpec(testDesiredSpec)),
			},
			want: want{
				cr:     application(withExternalName(testExternalNameID), withSpec(testDesiredSpec)),
				result: managed.ExternalObservation{ResourceExists: false},
			},
		},
		"NotFoundAfterMultiplePages": {
			args: args{
				client: &MockApplicationClient{
					MockListApplications: func() func(opt *gitlab.ListApplicationsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Application, *gitlab.Response, error) {
						page := int64(0)
						return func(opt *gitlab.ListApplicationsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Application, *gitlab.Response, error) {
							page++
							other := &gitlab.Application{ID: 99, ApplicationName: "other"}
							if page < 3 {
								return []*gitlab.Application{other}, &gitlab.Response{Response: &http.Response{StatusCode: 200}, NextPage: page + 1}, nil
							}
							return []*gitlab.Application{other}, &gitlab.Response{Response: &http.Response{StatusCode: 200}}, nil
						}
					}(),
				},
				cr: application(withExternalName(testExternalNameID), withSpec(testDesiredSpec)),
			},
			want: want{
				cr:     application(withExternalName(testExternalNameID), withSpec(testDesiredSpec)),
				result: managed.ExternalObservation{ResourceExists: false},
			},
		},
		"FoundOnSecondPage": {
			args: args{
				client: &MockApplicationClient{
					MockListApplications: func() func(opt *gitlab.ListApplicationsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Application, *gitlab.Response, error) {
						page := int64(0)
						return func(opt *gitlab.ListApplicationsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Application, *gitlab.Response, error) {
							page++
							if page == 1 {
								other := &gitlab.Application{ID: 99, ApplicationName: "other"}
								return []*gitlab.Application{other}, &gitlab.Response{Response: &http.Response{StatusCode: 200}, NextPage: 2}, nil
							}
							return []*gitlab.Application{testApp}, &gitlab.Response{Response: &http.Response{StatusCode: 200}}, nil
						}
					}(),
				},
				cr: application(withExternalName(testExternalNameID), withSpec(testDesiredSpec)),
			},
			want: want{
				cr: application(
					withExternalName(testExternalNameID),
					withSpec(testDesiredSpec),
					withConditions(v2.Available()),
					withAtProvider(instanceclient.GenerateApplicationObservation(testApp)),
				),
				result: managed.ExternalObservation{ResourceExists: true, ResourceUpToDate: true},
			},
		},
		"ListErrorOnSecondPage": {
			args: args{
				client: &MockApplicationClient{
					MockListApplications: func() func(opt *gitlab.ListApplicationsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Application, *gitlab.Response, error) {
						page := int64(0)
						return func(opt *gitlab.ListApplicationsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Application, *gitlab.Response, error) {
							page++
							if page == 1 {
								other := &gitlab.Application{ID: 99, ApplicationName: "other"}
								return []*gitlab.Application{other}, &gitlab.Response{Response: &http.Response{StatusCode: 200}, NextPage: 2}, nil
							}
							return nil, &gitlab.Response{Response: &http.Response{StatusCode: 500}}, errBoom
						}
					}(),
				},
				cr: application(withExternalName(testExternalNameID), withSpec(testDesiredSpec)),
			},
			want: want{
				cr:  application(withExternalName(testExternalNameID), withSpec(testDesiredSpec)),
				err: errors.Wrap(errBoom, errGetFailed),
			},
		},
		"FoundAndUpToDate": {
			args: args{
				client: &MockApplicationClient{
					MockListApplications: func(opt *gitlab.ListApplicationsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Application, *gitlab.Response, error) {
						return []*gitlab.Application{testApp}, &gitlab.Response{Response: &http.Response{StatusCode: 200}}, nil
					},
				},
				cr: application(withExternalName(testExternalNameID), withSpec(testDesiredSpec)),
			},
			want: want{
				cr: application(
					withExternalName(testExternalNameID),
					withSpec(testDesiredSpec),
					withConditions(v2.Available()),
					withAtProvider(instanceclient.GenerateApplicationObservation(testApp)),
				),
				result: managed.ExternalObservation{ResourceExists: true, ResourceUpToDate: true},
			},
		},
		"FoundAndNotUpToDate": {
			args: args{
				client: &MockApplicationClient{
					MockListApplications: func(opt *gitlab.ListApplicationsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Application, *gitlab.Response, error) {
						changed := *testApp
						changed.ApplicationName = "different-name"
						return []*gitlab.Application{&changed}, &gitlab.Response{Response: &http.Response{StatusCode: 200}}, nil
					},
				},
				cr: application(withExternalName(testExternalNameID), withSpec(testDesiredSpec)),
			},
			want: want{
				cr: application(
					withExternalName(testExternalNameID),
					withSpec(testDesiredSpec),
					withConditions(v2.Available()),
					withAtProvider(instanceclient.GenerateApplicationObservation(func() *gitlab.Application {
						a := *testApp
						a.ApplicationName = "different-name"
						return &a
					}())),
				),
				result: managed.ExternalObservation{ResourceExists: true, ResourceUpToDate: false},
			},
		},
		"RenewalDue": {
			args: args{
				client: &MockApplicationClient{
					MockListApplications: func(opt *gitlab.ListApplicationsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Application, *gitlab.Response, error) {
						return []*gitlab.Application{testApp}, &gitlab.Response{Response: &http.Response{StatusCode: 200}}, nil
					},
				},
				cr: application(
					withExternalName(testExternalNameID),
					withSpec(v1alpha1.ApplicationParameters{
						Name:              testAppName,
						RedirectURI:       testRedirectURI,
						Scopes:            []string{"api", "read_user"},
						RenewalPeriodDays: ptr.To(int64(30)),
					}),
					withAnnotations(map[string]string{instanceclient.AnnotationKeySecretRenewalDate: pastDate}),
				),
			},
			want: want{
				cr: application(
					withExternalName(testExternalNameID),
					withSpec(v1alpha1.ApplicationParameters{
						Name:              testAppName,
						RedirectURI:       testRedirectURI,
						Scopes:            []string{"api", "read_user"},
						RenewalPeriodDays: ptr.To(int64(30)),
					}),
					withAnnotations(map[string]string{instanceclient.AnnotationKeySecretRenewalDate: pastDate}),
					withConditions(v2.Available()),
					withAtProvider(instanceclient.GenerateApplicationObservation(testApp)),
					withNextRenewalAtStr(pastDate),
				),
				result: managed.ExternalObservation{ResourceExists: true, ResourceUpToDate: false},
			},
		},
		"RenewalNotDue": {
			args: args{
				client: &MockApplicationClient{
					MockListApplications: func(opt *gitlab.ListApplicationsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Application, *gitlab.Response, error) {
						return []*gitlab.Application{testApp}, &gitlab.Response{Response: &http.Response{StatusCode: 200}}, nil
					},
				},
				cr: application(
					withExternalName(testExternalNameID),
					withSpec(v1alpha1.ApplicationParameters{
						Name:              testAppName,
						RedirectURI:       testRedirectURI,
						Scopes:            []string{"api", "read_user"},
						RenewalPeriodDays: ptr.To(int64(30)),
					}),
					withAnnotations(map[string]string{instanceclient.AnnotationKeySecretRenewalDate: futureDate}),
				),
			},
			want: want{
				cr: application(
					withExternalName(testExternalNameID),
					withSpec(v1alpha1.ApplicationParameters{
						Name:              testAppName,
						RedirectURI:       testRedirectURI,
						Scopes:            []string{"api", "read_user"},
						RenewalPeriodDays: ptr.To(int64(30)),
					}),
					withAnnotations(map[string]string{instanceclient.AnnotationKeySecretRenewalDate: futureDate}),
					withConditions(v2.Available()),
					withAtProvider(instanceclient.GenerateApplicationObservation(testApp)),
					withNextRenewalAtStr(futureDate),
				),
				result: managed.ExternalObservation{ResourceExists: true, ResourceUpToDate: true},
			},
		},
		"RenewalPeriodSetButStatusMissing": {
			args: args{
				client: &MockApplicationClient{
					MockListApplications: func(opt *gitlab.ListApplicationsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Application, *gitlab.Response, error) {
						return []*gitlab.Application{testApp}, &gitlab.Response{Response: &http.Response{StatusCode: 200}}, nil
					},
				},
				cr: application(
					withExternalName(testExternalNameID),
					withSpec(v1alpha1.ApplicationParameters{
						Name:              testAppName,
						RedirectURI:       testRedirectURI,
						Scopes:            []string{"api", "read_user"},
						RenewalPeriodDays: ptr.To(int64(30)),
					}),
				),
			},
			want: want{
				cr: application(
					withExternalName(testExternalNameID),
					withSpec(v1alpha1.ApplicationParameters{
						Name:              testAppName,
						RedirectURI:       testRedirectURI,
						Scopes:            []string{"api", "read_user"},
						RenewalPeriodDays: ptr.To(int64(30)),
					}),
					withConditions(v2.Available()),
					withAtProvider(instanceclient.GenerateApplicationObservation(testApp)),
				),
				result: managed.ExternalObservation{ResourceExists: true, ResourceUpToDate: false},
			},
		},
	}

	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			e := &external{client: tc.args.client}
			got, err := e.Observe(context.Background(), tc.args.cr)
			if diff := cmp.Diff(tc.want.err, err, test.EquateErrors()); diff != "" {
				t.Errorf("Observe(): -want error, +got error:\n%s", diff)
			}
			if diff := cmp.Diff(tc.want.result, got); diff != "" {
				t.Errorf("Observe(): -want result, +got result:\n%s", diff)
			}
			if diff := cmp.Diff(tc.want.cr, tc.args.cr, test.EquateConditions()); diff != "" {
				t.Errorf("Observe(): -want cr, +got cr:\n%s", diff)
			}
		})
	}
}

func TestCreate(t *testing.T) {
	type want struct {
		cr     resource.Managed
		result managed.ExternalCreation
		err    error
	}

	cases := map[string]struct {
		args args
		want want
	}{
		"InvalidInput": {
			args: args{cr: unexpectedItem},
			want: want{cr: unexpectedItem, err: errors.New(errNotApplication)},
		},
		"NoConnectionRef": {
			args: args{cr: application(withSpec(testDesiredSpec))},
			want: want{
				cr:  application(withSpec(testDesiredSpec)),
				err: errors.New(errNoConnectionRef),
			},
		},
		"CreateError": {
			args: args{
				client: &MockApplicationClient{
					MockCreateApplication: func(opt *gitlab.CreateApplicationOptions, options ...gitlab.RequestOptionFunc) (*gitlab.Application, *gitlab.Response, error) {
						return nil, nil, errBoom
					},
				},
				cr: application(withSpec(testDesiredSpec), withConnectionSecretRef("test-secret")),
			},
			want: want{
				cr:  application(withSpec(testDesiredSpec), withConnectionSecretRef("test-secret"), withConditions(v2.Creating())),
				err: errors.Wrap(errBoom, errCreateFailed),
			},
		},
		"Successful": {
			args: args{
				client: &MockApplicationClient{
					MockCreateApplication: func(opt *gitlab.CreateApplicationOptions, options ...gitlab.RequestOptionFunc) (*gitlab.Application, *gitlab.Response, error) {
						return testApp, &gitlab.Response{Response: &http.Response{StatusCode: 201}}, nil
					},
				},
				cr: application(withSpec(testDesiredSpec), withConnectionSecretRef("test-secret")),
			},
			want: want{
				cr: application(
					withSpec(testDesiredSpec),
					withConnectionSecretRef("test-secret"),
					withExternalName(testExternalNameID),
					withConditions(v2.Creating()),
					withAtProvider(instanceclient.GenerateApplicationObservation(testApp)),
				),
				result: managed.ExternalCreation{
					ConnectionDetails: managed.ConnectionDetails{
						"secret":         []byte(testSecret),
						"application_id": []byte(testApplicationID),
					},
				},
			},
		},
		"SuccessfulWithRenewalPeriod": {
			args: args{
				client: &MockApplicationClient{
					MockCreateApplication: func(opt *gitlab.CreateApplicationOptions, options ...gitlab.RequestOptionFunc) (*gitlab.Application, *gitlab.Response, error) {
						return testApp, &gitlab.Response{Response: &http.Response{StatusCode: 201}}, nil
					},
				},
				cr: application(
					withSpec(v1alpha1.ApplicationParameters{
						Name:              testAppName,
						RedirectURI:       testRedirectURI,
						Scopes:            []string{"api", "read_user"},
						RenewalPeriodDays: ptr.To(int64(30)),
					}),
					withConnectionSecretRef("test-secret"),
				),
			},
			want: want{
				cr: application(
					withSpec(v1alpha1.ApplicationParameters{
						Name:              testAppName,
						RedirectURI:       testRedirectURI,
						Scopes:            []string{"api", "read_user"},
						RenewalPeriodDays: ptr.To(int64(30)),
					}),
					withConnectionSecretRef("test-secret"),
					withExternalName(testExternalNameID),
					withConditions(v2.Creating()),
					withAtProvider(instanceclient.GenerateApplicationObservation(testApp)),
					// renewal annotation is set but checked separately below
				),
				result: managed.ExternalCreation{
					ConnectionDetails: managed.ConnectionDetails{
						"secret":         []byte(testSecret),
						"application_id": []byte(testApplicationID),
					},
				},
			},
		},
	}

	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			e := &external{client: tc.args.client}
			got, err := e.Create(context.Background(), tc.args.cr)
			if diff := cmp.Diff(tc.want.err, err, test.EquateErrors()); diff != "" {
				t.Errorf("Create(): -want error, +got error:\n%s", diff)
			}
			if diff := cmp.Diff(tc.want.result, got); diff != "" {
				t.Errorf("Create(): -want result, +got result:\n%s", diff)
			}
			if name == "SuccessfulWithRenewalPeriod" {
				cr := tc.args.cr.(*v1alpha1.Application)
				if cr.GetAnnotations()[instanceclient.AnnotationKeySecretRenewalDate] == "" {
					t.Errorf("Create(): expected renewal annotation to be set")
				}
				return
			}
			if diff := cmp.Diff(tc.want.cr, tc.args.cr, test.EquateConditions()); diff != "" {
				t.Errorf("Create(): -want cr, +got cr:\n%s", diff)
			}
		})
	}
}

func TestUpdate(t *testing.T) {
	pastDate := time.Now().UTC().Add(-24 * time.Hour).Format(time.RFC3339)
	futureDate := time.Now().UTC().Add(48 * time.Hour).Format(time.RFC3339)
	newSecret := "newlyrenewedsecret"
	renewedApp := &gitlab.Application{
		ID:              42,
		ApplicationID:   testApplicationID,
		ApplicationName: testAppName,
		Secret:          newSecret,
		CallbackURL:     testRedirectURI,
	}

	type want struct {
		result managed.ExternalUpdate
		err    error
	}

	cases := map[string]struct {
		args args
		want want
	}{
		"InvalidInput": {
			args: args{cr: unexpectedItem},
			want: want{err: errors.New(errNotApplication)},
		},
		"NoRenewalPeriodReturnsError": {
			args: args{
				cr: application(withSpec(testDesiredSpec), withExternalName(testExternalNameID)),
			},
			want: want{err: errors.New(errCannotUpdate)},
		},
		"RenewalNotDueReturnsError": {
			args: args{
				cr: application(
					withExternalName(testExternalNameID),
					withSpec(v1alpha1.ApplicationParameters{
						Name:              testAppName,
						RedirectURI:       testRedirectURI,
						Scopes:            []string{"api", "read_user"},
						RenewalPeriodDays: ptr.To(int64(30)),
					}),
					withAnnotations(map[string]string{instanceclient.AnnotationKeySecretRenewalDate: futureDate}),
				),
			},
			want: want{err: errors.New(errCannotUpdate)},
		},
		"RenewSecretError": {
			args: args{
				client: &MockApplicationClient{
					MockRenewApplicationSecret: func(application int64, options ...gitlab.RequestOptionFunc) (*gitlab.Application, *gitlab.Response, error) {
						return nil, &gitlab.Response{Response: &http.Response{StatusCode: 500}}, errBoom
					},
				},
				cr: application(
					withExternalName(testExternalNameID),
					withSpec(v1alpha1.ApplicationParameters{
						Name:              testAppName,
						RedirectURI:       testRedirectURI,
						Scopes:            []string{"api", "read_user"},
						RenewalPeriodDays: ptr.To(int64(30)),
					}),
					withAnnotations(map[string]string{instanceclient.AnnotationKeySecretRenewalDate: pastDate}),
				),
			},
			want: want{err: errors.Wrap(errBoom, errRenewFailed)},
		},
		"RenewalDueAndSuccessful": {
			args: args{
				client: &MockApplicationClient{
					MockRenewApplicationSecret: func(application int64, options ...gitlab.RequestOptionFunc) (*gitlab.Application, *gitlab.Response, error) {
						return renewedApp, &gitlab.Response{Response: &http.Response{StatusCode: 200}}, nil
					},
				},
				cr: application(
					withExternalName(testExternalNameID),
					withSpec(v1alpha1.ApplicationParameters{
						Name:              testAppName,
						RedirectURI:       testRedirectURI,
						Scopes:            []string{"api", "read_user"},
						RenewalPeriodDays: ptr.To(int64(30)),
					}),
					withAnnotations(map[string]string{instanceclient.AnnotationKeySecretRenewalDate: pastDate}),
				),
			},
			want: want{
				result: managed.ExternalUpdate{
					ConnectionDetails: managed.ConnectionDetails{
						"secret":         []byte(newSecret),
						"application_id": []byte(testApplicationID),
					},
				},
			},
		},
		"RenewalWithMissingStatus": {
			args: args{
				client: &MockApplicationClient{
					MockRenewApplicationSecret: func(application int64, options ...gitlab.RequestOptionFunc) (*gitlab.Application, *gitlab.Response, error) {
						return renewedApp, &gitlab.Response{Response: &http.Response{StatusCode: 200}}, nil
					},
				},
				cr: application(
					withExternalName(testExternalNameID),
					withSpec(v1alpha1.ApplicationParameters{
						Name:              testAppName,
						RedirectURI:       testRedirectURI,
						Scopes:            []string{"api", "read_user"},
						RenewalPeriodDays: ptr.To(int64(30)),
					}),
				),
			},
			want: want{
				result: managed.ExternalUpdate{
					ConnectionDetails: managed.ConnectionDetails{
						"secret":         []byte(newSecret),
						"application_id": []byte(testApplicationID),
					},
				},
			},
		},
		"NonIntegerExternalNameWithRenewalDue": {
			args: args{
				cr: application(
					withExternalName("not-an-int"),
					withSpec(v1alpha1.ApplicationParameters{
						Name:              testAppName,
						RedirectURI:       testRedirectURI,
						Scopes:            []string{"api", "read_user"},
						RenewalPeriodDays: ptr.To(int64(30)),
					}),
					withAnnotations(map[string]string{instanceclient.AnnotationKeySecretRenewalDate: pastDate}),
				),
			},
			want: want{err: errors.New(errIDNotInt)},
		},
	}

	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			e := &external{client: tc.args.client}
			got, err := e.Update(context.Background(), tc.args.cr)
			if diff := cmp.Diff(tc.want.err, err, test.EquateErrors()); diff != "" {
				t.Errorf("Update(): -want error, +got error:\n%s", diff)
			}
			if diff := cmp.Diff(tc.want.result, got); diff != "" {
				t.Errorf("Update(): -want result, +got result:\n%s", diff)
			}
			// After a successful renewal, the renewal annotation must be set to a future time.
			if err == nil && name != "InvalidInput" {
				cr := tc.args.cr.(*v1alpha1.Application)
				renewalDate := cr.GetAnnotations()[instanceclient.AnnotationKeySecretRenewalDate]
				if renewalDate == "" {
					t.Errorf("Update(): expected renewal annotation to be set after renewal")
				} else {
					parsed, parseErr := time.Parse(time.RFC3339, renewalDate)
					if parseErr != nil || !parsed.After(time.Now().UTC()) {
						t.Errorf("Update(): expected renewal annotation to be a future time, got %v", renewalDate)
					}
				}
			}
		})
	}
}

func TestDelete(t *testing.T) {
	type want struct {
		result managed.ExternalDelete
		err    error
	}

	cases := map[string]struct {
		args args
		want want
	}{
		"InvalidInput": {
			args: args{cr: unexpectedItem},
			want: want{err: errors.New(errNotApplication)},
		},
		"NoExternalName": {
			args: args{cr: application(withSpec(testDesiredSpec))},
			want: want{result: managed.ExternalDelete{}},
		},
		"NonIntegerExternalName": {
			args: args{cr: application(withSpec(testDesiredSpec), withExternalName("not-an-int"))},
			want: want{err: errors.New(errIDNotInt)},
		},
		"DeleteError": {
			args: args{
				client: &MockApplicationClient{
					MockDeleteApplication: func(application int64, options ...gitlab.RequestOptionFunc) (*gitlab.Response, error) {
						return &gitlab.Response{Response: &http.Response{StatusCode: 500}}, errBoom
					},
				},
				cr: application(withSpec(testDesiredSpec), withExternalName(testExternalNameID)),
			},
			want: want{err: errors.Wrap(errBoom, errDeleteFailed)},
		},
		"DeleteNotFound": {
			args: args{
				client: &MockApplicationClient{
					MockDeleteApplication: func(application int64, options ...gitlab.RequestOptionFunc) (*gitlab.Response, error) {
						return &gitlab.Response{Response: &http.Response{StatusCode: 404}}, errBoom
					},
				},
				cr: application(withSpec(testDesiredSpec), withExternalName(testExternalNameID)),
			},
			want: want{err: errors.Wrap(errBoom, errDeleteFailed)},
		},
		"Successful": {
			args: args{
				client: &MockApplicationClient{
					MockDeleteApplication: func(application int64, options ...gitlab.RequestOptionFunc) (*gitlab.Response, error) {
						return &gitlab.Response{Response: &http.Response{StatusCode: 204}}, nil
					},
				},
				cr: application(withSpec(testDesiredSpec), withExternalName(testExternalNameID)),
			},
			want: want{result: managed.ExternalDelete{}},
		},
	}

	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			e := &external{client: tc.args.client}
			got, err := e.Delete(context.Background(), tc.args.cr)
			if diff := cmp.Diff(tc.want.err, err, test.EquateErrors()); diff != "" {
				t.Errorf("Delete(): -want error, +got error:\n%s", diff)
			}
			if diff := cmp.Diff(tc.want.result, got); diff != "" {
				t.Errorf("Delete(): -want result, +got result:\n%s", diff)
			}
		})
	}
}

func TestDisconnect(t *testing.T) {
	e := &external{}
	if err := e.Disconnect(context.Background()); err != nil {
		t.Errorf("Disconnect(): unexpected error: %v", err)
	}
}

func TestDeleteWithCondition(t *testing.T) {
	cr := application(withSpec(testDesiredSpec), withExternalName(testExternalNameID))
	e := &external{
		client: &MockApplicationClient{
			MockDeleteApplication: func(application int64, options ...gitlab.RequestOptionFunc) (*gitlab.Response, error) {
				return &gitlab.Response{Response: &http.Response{StatusCode: 204}}, nil
			},
		},
	}
	_, err := e.Delete(context.Background(), cr)
	if err != nil {
		t.Fatalf("Delete(): unexpected error: %v", err)
	}
	want := application(withSpec(testDesiredSpec), withExternalName(testExternalNameID), withConditions(v2.Deleting()))
	if diff := cmp.Diff(want, cr, test.EquateConditions()); diff != "" {
		t.Errorf("Delete() condition: -want, +got:\n%s", diff)
	}
}

func TestObserveWithConfidentialMismatch(t *testing.T) {
	confTrue := true
	specWithConf := v1alpha1.ApplicationParameters{
		Name:         testAppName,
		RedirectURI:  testRedirectURI,
		Scopes:       []string{"api", "read_user"},
		Confidential: &confTrue,
	}
	cr := application(withExternalName(testExternalNameID), withSpec(specWithConf))
	e := &external{
		client: &MockApplicationClient{
			MockListApplications: func(opt *gitlab.ListApplicationsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Application, *gitlab.Response, error) {
				return []*gitlab.Application{testApp}, &gitlab.Response{Response: &http.Response{StatusCode: 200}}, nil
			},
		},
	}
	got, err := e.Observe(context.Background(), cr)
	if err != nil {
		t.Fatalf("Observe(): unexpected error: %v", err)
	}
	if got.ResourceUpToDate {
		t.Errorf("Observe(): expected ResourceUpToDate=false when Confidential differs")
	}
	_ = bPtr(true)
}
