---
# Gitlab credentials secret
apiVersion: v1
kind: Secret
metadata:
  name: example-creds
  namespace: crossplane-system
type: Opaque
data:
  token: <REPLACEME>
---
# Gitlab provider that references the secret credentials
apiVersion: gitlab.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: example
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: example-creds
      key: token
