---
# Gitlab provider that references the secret credentials
apiVersion: gitlab.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: gitlab-provider
spec:
  baseURL: https://gitlab.com/
  credentials:
    source: Secret
    method: OAuthToken # method of authentification can be BasicAuth, JobToken, OAuthToken or PrivateToken (default)
    secretRef:
      namespace: crossplane-system
      name: gitlab-credentials
      key: token
