/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by hack/generate-cluster-scope.go - DO NOT EDIT.

package groups

import (
	"testing"
	"time"

	"github.com/google/go-cmp/cmp"
	gitlab "gitlab.com/gitlab-org/api/client-go"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	"github.com/crossplane-contrib/provider-gitlab/apis/cluster/groups/v1alpha1"
)

func TestGenerateCreateGroupAccessTokenOptions(t *testing.T) {
	name := "Name"
	var expiresAt time.Time
	scopes := []string{"scope1", "scope2"}
	accessLevel := 40
	type args struct {
		name       string
		parameters *v1alpha1.AccessTokenParameters
	}
	cases := map[string]struct {
		args args
		want *gitlab.CreateGroupAccessTokenOptions
	}{
		"AllFields": {
			args: args{
				name: name,
				parameters: &v1alpha1.AccessTokenParameters{
					Name:        name,
					AccessLevel: (*v1alpha1.AccessLevelValue)(&accessLevel),
					ExpiresAt:   &v1.Time{Time: expiresAt},
					Scopes:      scopes,
				},
			},
			want: &gitlab.CreateGroupAccessTokenOptions{
				Name:        &name,
				AccessLevel: (*gitlab.AccessLevelValue)(&accessLevel),
				ExpiresAt:   (*gitlab.ISOTime)(&expiresAt),
				Scopes:      &scopes,
			},
		},
		"noExpiresAt": {
			args: args{
				name: name,
				parameters: &v1alpha1.AccessTokenParameters{
					Name:        name,
					AccessLevel: (*v1alpha1.AccessLevelValue)(&accessLevel),
					ExpiresAt:   nil,
					Scopes:      scopes,
				},
			},
			want: &gitlab.CreateGroupAccessTokenOptions{
				Name:        &name,
				AccessLevel: (*gitlab.AccessLevelValue)(&accessLevel),
				ExpiresAt:   nil,
				Scopes:      &scopes,
			},
		},
	}
	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			got := GenerateCreateGroupAccessTokenOptions(tc.args.name, tc.args.parameters)

			// Compare fields individually since gitlab.ISOTime has unexported fields
			if tc.want.Name != nil && got.Name != nil && *tc.want.Name != *got.Name {
				t.Errorf("Name: want %v, got %v", *tc.want.Name, *got.Name)
			}

			if tc.want.AccessLevel != nil && got.AccessLevel != nil && *tc.want.AccessLevel != *got.AccessLevel {
				t.Errorf("AccessLevel: want %v, got %v", *tc.want.AccessLevel, *got.AccessLevel)
			}

			if tc.want.ExpiresAt != nil && got.ExpiresAt != nil {
				wantTime := time.Time(*tc.want.ExpiresAt)
				gotTime := time.Time(*got.ExpiresAt)
				wantDay := wantTime.Truncate(24 * time.Hour)
				gotDay := gotTime.Truncate(24 * time.Hour)
				if !wantDay.Equal(gotDay) {
					t.Errorf("ExpiresAt: want %v, got %v", wantDay, gotDay)
				}
			} else if tc.want.ExpiresAt != got.ExpiresAt {
				t.Errorf("ExpiresAt: want %v, got %v", tc.want.ExpiresAt, got.ExpiresAt)
			}

			if diff := cmp.Diff(tc.want.Scopes, got.Scopes); diff != "" {
				t.Errorf("Scopes: -want, +got:\n%s", diff)
			}
		})
	}
}
