//go:build ignore
// +build ignore

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

func main() {
	if len(os.Args) < 2 {
		printUsage()
		os.Exit(1)
	}

	switch os.Args[1] {
	case "generate":
		handleGenerate(os.Args[2:])
	case "backup-referencers":
		handleCommand(backupReferencers, "backed up")
	case "restore-referencers":
		handleCommand(restoreReferencers, "restored")
	default:
		fmt.Fprintf(os.Stderr, "Unknown command: %s\n", os.Args[1])
		printUsage()
		os.Exit(1)
	}
}

// printUsage displays the usage instructions for the script.
func printUsage() {
	fmt.Println("Usage:")
	fmt.Println("  generate <folder1> [folder2] ...  - Generate cluster scope files")
	fmt.Println("  backup-referencers               - Backup referencers files")
	fmt.Println("  restore-referencers              - Restore referencers files")
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Println("  generate groups projects")
	fmt.Println("  generate clients")
}

// handleGenerate processes the generate command with the provided folders.
func handleGenerate(args []string) {
	if len(args) < 1 {
		fmt.Fprintf(os.Stderr, "generate command requires at least one folder\n")
		printUsage()
		os.Exit(1)
	}

	if err := generateClusterScope(args); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("Successfully generated cluster scope for folders: %v\n", args)
}

// handleCommand executes the given function and handles errors uniformly.
func handleCommand(fn func() error, action string) {
	if err := fn(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("Successfully %s referencers files\n", action)
}

// generateClusterScope generates cluster-scoped resource files
// from namespaced resource files in the specified folders.
func generateClusterScope(folders []string) error {
	namespacedPath := "namespaced"
	clusterPath := "cluster"

	if err := validateAndSetup(namespacedPath, clusterPath, folders); err != nil {
		return err
	}

	for _, folder := range folders {
		if err := processFolder(namespacedPath, clusterPath, folder); err != nil {
			return fmt.Errorf("failed to process folder %s: %w", folder, err)
		}
	}

	return nil
}

// validateAndSetup checks the existence of the namespaced directory,
// creates the cluster directory if it doesn't exist, and cleans up
// any existing cluster folders that will be regenerated.
func validateAndSetup(namespacedPath, clusterPath string, folders []string) error {
	if _, err := os.Stat(namespacedPath); os.IsNotExist(err) {
		return fmt.Errorf("namespaced directory does not exist at %s", namespacedPath)
	}

	if err := os.MkdirAll(clusterPath, 0755); err != nil {
		return fmt.Errorf("failed to create cluster directory: %w", err)
	}

	for _, folder := range folders {
		targetFolder := filepath.Join(clusterPath, folder)
		if err := os.RemoveAll(targetFolder); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("failed to remove cluster folder %s: %w", targetFolder, err)
		}
	}

	return nil
}

// processFolder processes all files in the specified folder, applying necessary transformations.
func processFolder(namespacedPath, clusterPath, folder string) error {
	folderPath := filepath.Join(namespacedPath, folder)
	if _, err := os.Stat(folderPath); os.IsNotExist(err) {
		fmt.Printf("Warning: folder %s does not exist, skipping\n", folderPath)
		return nil
	}

	if err := filepath.WalkDir(folderPath, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		// Skip zz_ files in the main walk - they are handled separately below.
		// Most zz_ files are generated by controller-gen/angryjet and should not be copied.
		if strings.HasPrefix(d.Name(), "zz_") {
			return nil
		}

		targetPath := strings.Replace(path, namespacedPath, clusterPath, 1)

		if d.IsDir() {
			return os.MkdirAll(targetPath, 0755)
		}

		if strings.HasSuffix(path, ".go") && !shouldSkipFile(path) {
			dir := filepath.Dir(targetPath)
			filename := filepath.Base(targetPath)
			targetPath = filepath.Join(dir, "zz_"+filename)
			return transformFile(path, targetPath)
		}

		return nil
	}); err != nil {
		return err
	}

	// WORKAROUND: Copy and transform zz_generated.managed.go and zz_generated.managedlist.go files.
	// The angryjet tool (crossplane-tools) only recognizes types embedding ManagedResourceSpec from
	// crossplane-runtime, but cluster-scoped resources embed ClusterManagedResourceSpec from the
	// crossplane core v2 API. Until crossplane-tools adds support for ClusterManagedResourceSpec,
	// we copy and transform these files from the namespaced version.
	// See: https://github.com/crossplane/crossplane-tools/blob/master/internal/fields/fields.go
	return copyGeneratedManagedFiles(namespacedPath, clusterPath, folder)
}

// copyGeneratedManagedFiles copies and transforms zz_generated.managed.go and zz_generated.managedlist.go
// from the namespaced folder to the cluster folder.
// This is a workaround because angryjet (crossplane-tools) does not recognize ClusterManagedResourceSpec.
func copyGeneratedManagedFiles(namespacedPath, clusterPath, folder string) error {
	filesToCopy := []string{
		"zz_generated.managed.go",
		"zz_generated.managedlist.go",
		"zz_generated.resolvers.go",
	}

	// Walk through all version directories (e.g., v1alpha1, v1beta1)
	folderPath := filepath.Join(namespacedPath, folder)
	return filepath.WalkDir(folderPath, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if d.IsDir() {
			return nil
		}

		// Check if this is one of the files we need to copy
		for _, filename := range filesToCopy {
			if d.Name() == filename {
				targetPath := strings.Replace(path, namespacedPath, clusterPath, 1)
				if err := transformGeneratedManagedFile(path, targetPath); err != nil {
					return fmt.Errorf("failed to copy %s: %w", path, err)
				}
			}
		}

		return nil
	})
}

// transformGeneratedManagedFile transforms a zz_generated.managed.go or zz_generated.managedlist.go
// file for cluster scope, applying necessary type replacements.
func transformGeneratedManagedFile(srcPath, dstPath string) error {
	content, err := os.ReadFile(srcPath)
	if err != nil {
		return fmt.Errorf("failed to read %s: %w", srcPath, err)
	}

	transformed := string(content)

	// Replace the angryjet comment with our own generation comment
	transformed = strings.Replace(
		transformed,
		"// Code generated by angryjet. DO NOT EDIT.",
		"// Code generated by hack/generate-cluster-scope.go from namespaced version - DO NOT EDIT.\n// WORKAROUND: angryjet does not support ClusterManagedResourceSpec, see processFolder() for details.",
		1,
	)

	// Apply the standard replacements for cluster scope
	for _, r := range getReplacements() {
		transformed = strings.ReplaceAll(transformed, r.old, r.new)
	}

	// For zz_generated.managed.go files, add DeletionPolicy methods.
	// ClusterManagedResourceSpec has DeletionPolicy but ManagedResourceSpec doesn't,
	// so we need to inject these methods for each resource type.
	if strings.HasSuffix(srcPath, "zz_generated.managed.go") {
		transformed = addDeletionPolicyMethods(transformed)
	}

	// Format the code
	if formatted, err := format.Source([]byte(transformed)); err == nil {
		transformed = string(formatted)
	}

	return os.WriteFile(dstPath, []byte(transformed), 0644)
}

// addDeletionPolicyMethods injects GetDeletionPolicy and SetDeletionPolicy methods
// for each resource type found in the file. This is needed because ClusterManagedResourceSpec
// has a DeletionPolicy field that ManagedResourceSpec lacks.
func addDeletionPolicyMethods(content string) string {
	// Find all resource types by matching "// GetCondition of this <Type>."
	re := regexp.MustCompile(`// GetCondition of this (\w+)\.`)
	matches := re.FindAllStringSubmatch(content, -1)

	for _, match := range matches {
		typeName := match[1]

		// Find the SetManagementPolicies method for this type and add DeletionPolicy methods after it
		setMgmtPattern := fmt.Sprintf(
			"// SetManagementPolicies of this %s.\nfunc (mg *%s) SetManagementPolicies(r v2.ManagementPolicies) {\n\tmg.Spec.ManagementPolicies = r\n}",
			typeName, typeName,
		)

		deletionPolicyMethods := fmt.Sprintf(
			"// SetManagementPolicies of this %s.\nfunc (mg *%s) SetManagementPolicies(r v2.ManagementPolicies) {\n\tmg.Spec.ManagementPolicies = r\n}\n\n"+
				"// GetDeletionPolicy of this %s.\nfunc (mg *%s) GetDeletionPolicy() v2.DeletionPolicy {\n\treturn mg.Spec.DeletionPolicy\n}\n\n"+
				"// SetDeletionPolicy of this %s.\nfunc (mg *%s) SetDeletionPolicy(r v2.DeletionPolicy) {\n\tmg.Spec.DeletionPolicy = r\n}",
			typeName, typeName,
			typeName, typeName,
			typeName, typeName,
		)

		content = strings.Replace(content, setMgmtPattern, deletionPolicyMethods, 1)
	}

	return content
}

// shouldSkipFile checks if the file contains the +cluster-scope:skip-file annotation.
func shouldSkipFile(filePath string) bool {
	content, err := os.ReadFile(filePath)
	if err != nil {
		return false
	}
	return strings.Contains(string(content), "+cluster-scope:skip-file")
}

// transformFile reads the source file, applies transformations,
// and writes the result to the destination file.
func transformFile(srcPath, dstPath string) error {
	content, err := os.ReadFile(srcPath)
	if err != nil {
		return fmt.Errorf("failed to read %s: %w", srcPath, err)
	}

	transformed := transformContent(string(content))

	if formatted, err := format.Source([]byte(transformed)); err == nil {
		transformed = string(formatted)
	}

	return os.WriteFile(dstPath, []byte(transformed), 0644)
}

// processDeleteAnnotations removes lines based on +cluster-scope:delete=N annotations.
func processDeleteAnnotations(content string) string {
	lines := strings.Split(content, "\n")
	var result []string

	for i := 0; i < len(lines); i++ {
		line := lines[i]

		if idx := strings.Index(line, "+cluster-scope:delete="); idx != -1 {
			numStr := strings.TrimSpace(line[idx+len("+cluster-scope:delete="):])
			if num, err := strconv.Atoi(numStr); err == nil && num > 0 {
				i += num
				continue
			}
		}

		result = append(result, line)
	}

	return strings.Join(result, "\n")
}

// transformContent applies all necessary transformations to convert
// namespaced resource code to cluster-scoped resource code.
func transformContent(content string) string {
	content = processDeleteAnnotations(content)
	content = addGenerationComment(content)

	for _, r := range getReplacements() {
		content = strings.ReplaceAll(content, r.old, r.new)
	}

	return content
}

// addGenerationComment adds a code generation comment at the top of the file.
func addGenerationComment(content string) string {
	lines := strings.Split(content, "\n")
	for i, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), "package ") {
			result := make([]string, 0, len(lines)+2)
			result = append(result, lines[:i]...)
			result = append(result, "// Code generated by hack/generate-cluster-scope.go - DO NOT EDIT.", "")
			result = append(result, lines[i:]...)
			return strings.Join(result, "\n")
		}
	}
	return content
}

// replacement defines a string replacement rule.
type replacement struct {
	old, new string
}

// getReplacements returns a list of string replacements to convert
// This is important to keep a list structure to ensure priority of replacements.
func getReplacements() []replacement {
	return []replacement{
		// Add .cluster suffix to controller names to avoid conflicts with namespaced controllers
		{"managed.ControllerName(", "managed.ControllerName(\"cluster.\" + "},
		{"m.crossplane.io", "crossplane.io"},
		{"v2.ManagedResourceSpec", "v2.ClusterManagedResourceSpec"},
		{"v2.NamespacedReference", "v2.Reference"},
		{"v2.NamespacedSelector", "v2.Selector"},
		{"v2.LocalSecretKeySelector", "v2.SecretKeySelector"},
		{"v2.LocalSecretReference", "v2.SecretReference"},
		{"LocalSecretReference:", "SecretReference:"},
		{".LocalSecretReference", ".SecretReference"},
		{"reference.NewAPINamespacedResolver", "reference.NewAPIResolver"},
		{"reference.NamespacedResolutionRequest", "reference.ResolutionRequest"},
		{"reference.NamespacedResolutionResponse", "reference.ResolutionResponse"},
		{"kubebuilder:resource:scope=Namespaced", "kubebuilder:resource:scope=Cluster"},
		{"/namespaced/", "/cluster/"},
		{"GetTokenValueFromLocalSecret", "GetTokenValueFromSecret"},
		{"TestCreateLocalSecretKeySelector", "TestCreateSecretKeySelector"},
		{"TestCreateLocalSecretReference", "TestCreateSecretReference"},
		// ClusterManagedResourceSpec uses Reference instead of ProviderConfigReference
		// for the ProviderConfigReference field (needed for zz_generated.managed.go transformation)
		{"v2.ProviderConfigReference", "v2.Reference"},
	}
}

// backupReferencers backs up all referencers.go files by renaming them with a .bak extension.
func backupReferencers() error {
	return filepath.WalkDir(".", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if strings.HasSuffix(path, "referencers.go") && !strings.HasSuffix(path, ".bak") {
			return os.Rename(path, path+".bak")
		}
		return nil
	})
}

// restoreReferencers restores all referencers.go.bak files by renaming them back to referencers.go.
func restoreReferencers() error {
	return filepath.WalkDir(".", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if strings.HasSuffix(path, "referencers.go.bak") {
			return os.Rename(path, strings.TrimSuffix(path, ".bak"))
		}
		return nil
	})
}
