apiVersion: groups.gitlab.crossplane.io/v1alpha1
kind: AccessToken
metadata:
  name: example-group-access-token
spec:
  forProvider:
    name: example-group-access-token
    groupIdRef:
      name: example-group
    accessLevel: 40
    expiresAt: "2025-06-15T08:00:00Z"
    scopes:
      - "read_repository"
  providerConfigRef:
    name: gitlab-provider
  writeConnectionSecretToRef:
    name: gitlab-example-group-access-token
    namespace: crossplane-system
---
apiVersion: groups.gitlab.crossplane.io/v1alpha1
kind: AccessToken
metadata:
  name: example-group-access-token-no-expiry
spec:
  forProvider:
    name: example-group-access-token-no-expiry
    groupIdRef:
      name: example-group
    accessLevel: 40
    expiresAt: null # This configures the expiration date to the maximum allowable lifetime limit set by GitLab instance
    scopes:
      - "read_repository"
  providerConfigRef:
    name: gitlab-provider
  writeConnectionSecretToRef:
    name: gitlab-example-group-access-token-no-expiry
    namespace: crossplane-system
