---
apiVersion: groups.gitlab.m.crossplane.io/v1alpha1
kind: AccessToken
metadata:
  name: example-group-access-token
  namespace: default
spec:
  forProvider:
    name: example-group-access-token
    groupIdRef:
      name: example-group
    accessLevel: 40
    expiresAt: "2026-06-15T08:00:00Z"
    scopes:
      - "read_repository"
  providerConfigRef:
    name: gitlab-provider
    kind: ProviderConfig
  writeConnectionSecretToRef:
    name: gitlab-example-group-access-token
---
apiVersion: groups.gitlab.m.crossplane.io/v1alpha1
kind: AccessToken
metadata:
  name: example-group-access-token-no-expiry
  namespace: default
spec:
  forProvider:
    name: example-group-access-token-no-expiry
    groupIdRef:
      name: example-group
    accessLevel: 40
    renewalPeriodDays: 5
    scopes:
      - "read_repository"
  providerConfigRef:
    name: gitlab-provider
    kind: ProviderConfig
  writeConnectionSecretToRef:
    name: gitlab-example-group-access-token-no-expiry
