apiVersion: groups.gitlab.crossplane.io/v1alpha1
kind: Group
metadata:
  name: example-group
spec:
  forProvider:
    parentId: 12345678
    path: "example-path-11358079"
    description: "an group description"
  providerConfigRef:
    name: gitlab-provider
  # a reference to a Kubernetes secret to which the controller will write the runnersToken
  writeConnectionSecretToRef:
    name: gitlab-group-example-group
    namespace: crossplane-system
