apiVersion: groups.gitlab.crossplane.io/v1alpha1
kind: Group
metadata:
  name: example-group
spec:
  forProvider:
    # If not set, metadata.name will be used instead.
    name: "Example Group"
    parentIdRef:
      name: example-parent-group
    path: "example-group-path"
    description: "example group description"
  providerConfigRef:
    name: gitlab-provider
  # a reference to a Kubernetes secret to which the controller will write the runnersToken
  writeConnectionSecretToRef:
    name: gitlab-group-example-group
    namespace: crossplane-system
