apiVersion: groups.gitlab.crossplane.io/v1alpha1
kind: GroupMember
metadata:
  name: example-group-member
spec:
  forProvider:
    groupID: 11358079
    userID: 8777466
    accessLevel: 20
    # expiresAt: "2021-06-09"
  providerConfigRef:
    name: gitlab-provider
  # a reference to a Kubernetes secret to which the controller will write the runnersToken
  writeConnectionSecretToRef:
    name: gitlab-group-example-groupmember
    namespace: crossplane-system
