---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-credentials
  namespace: default
type: Opaque
stringData:
  password: "supersecret"
---
apiVersion: groups.gitlab.m.crossplane.io/v1alpha1
kind: IntegrationHarbor
metadata:
  name: harbor-g7
  namespace: default
spec:
  providerConfigRef:
    name: gitlab-provider
    kind: ProviderConfig
  forProvider:
    groupId: 42
    url: "https://demo.goharbor.io"
    projectName: "mygroupproject"
    username: "robot$gitlab"
    passwordSecretRef:
      name: harbor-credentials
      key: password
