# Example UserRunner for a GitLab group
# IMPORTANT: The writeConnectionSecretToRef is REQUIRED to receive the runner token.
# Without this, the runner cannot be registered and is unusable.
apiVersion: groups.gitlab.crossplane.io/v1alpha1
kind: UserRunner
metadata:
  name: example-group-runner
spec:
  forProvider:
    groupIdRef:
      name: example-group
    description: "example group runner description"
    tagList:
      - "example-tag-1"
      - "example-tag-2"
  providerConfigRef:
    name: gitlab-provider
  # REQUIRED: This creates a Kubernetes secret containing the runner token
  # The token is needed to register the GitLab Runner agent
  writeConnectionSecretToRef:
    name: gitlab-example-group-runner-token
    namespace: crossplane-system