/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by hack/generate-cluster-scope.go - DO NOT EDIT.

package projects

import (
	"strings"
	"time"

	gitlab "gitlab.com/gitlab-org/api/client-go"
	"k8s.io/utils/ptr"

	"github.com/crossplane-contrib/provider-gitlab/apis/cluster/projects/v1alpha1"
	"github.com/crossplane-contrib/provider-gitlab/pkg/common"
)

// AccessTokenClient defines Gitlab Project service operations
type AccessTokenClient interface {
	GetProjectAccessToken(pid interface{}, id int64, options ...gitlab.RequestOptionFunc) (*gitlab.ProjectAccessToken, *gitlab.Response, error)
	CreateProjectAccessToken(pid interface{}, opt *gitlab.CreateProjectAccessTokenOptions, options ...gitlab.RequestOptionFunc) (*gitlab.ProjectAccessToken, *gitlab.Response, error)
	RevokeProjectAccessToken(pid interface{}, id int64, options ...gitlab.RequestOptionFunc) (*gitlab.Response, error)
	RotateProjectAccessToken(pid interface{}, id int64, opt *gitlab.RotateProjectAccessTokenOptions, options ...gitlab.RequestOptionFunc) (*gitlab.ProjectAccessToken, *gitlab.Response, error)
	RotateSelf(opt *gitlab.RotatePersonalAccessTokenOptions, options ...gitlab.RequestOptionFunc) (*gitlab.PersonalAccessToken, *gitlab.Response, error)
}

// IsErrorProjectAccessTokenNotFound helper function to test for errProjectAccessTokenNotFound error.
func IsErrorProjectAccessTokenNotFound(err error) bool {
	if err == nil {
		return false
	}
	return strings.Contains(err.Error(), errProjectNotFound)
}

// NewAccessTokenClient returns a new Gitlab ProjectAccessToken service
func NewAccessTokenClient(cfg common.Config) AccessTokenClient {
	git := common.NewClient(cfg)
	return &accessTokenClient{
		ProjectAccessTokensServiceInterface:  git.ProjectAccessTokens,
		PersonalAccessTokensServiceInterface: git.PersonalAccessTokens,
	}
}

// accessTokenClient composes project and personal access token services.
type accessTokenClient struct {
	gitlab.ProjectAccessTokensServiceInterface
	gitlab.PersonalAccessTokensServiceInterface
}

func (c *accessTokenClient) RotateSelf(opt *gitlab.RotatePersonalAccessTokenOptions, options ...gitlab.RequestOptionFunc) (*gitlab.PersonalAccessToken, *gitlab.Response, error) {
	return c.PersonalAccessTokensServiceInterface.RotatePersonalAccessTokenSelf(opt, options...)
}

// GenerateCreateProjectAccessTokenOptions generates project creation options
func GenerateCreateProjectAccessTokenOptions(name string, p *v1alpha1.AccessTokenParameters) *gitlab.CreateProjectAccessTokenOptions {
	accesstoken := &gitlab.CreateProjectAccessTokenOptions{
		Name:   &p.Name,
		Scopes: &p.Scopes,
	}

	if p.ExpiresAt != nil {
		accesstoken.ExpiresAt = (*gitlab.ISOTime)(&p.ExpiresAt.Time)
	} else if p.RenewalPeriodDays != nil {
		accesstoken.ExpiresAt = common.GenerateRenewalExpiration(*p.RenewalPeriodDays)
	}

	if p.AccessLevel != nil {
		accesstoken.AccessLevel = (*gitlab.AccessLevelValue)(p.AccessLevel)
	}

	if p.Description != nil {
		accesstoken.Description = ptr.To(*p.Description)
	}

	return accesstoken
}

// GenerateProjectAccessTokenObservation generates project access token observation from gitlab.ProjectAccessToken.
func GenerateProjectAccessTokenObservation(at *gitlab.ProjectAccessToken) v1alpha1.AccessTokenObservation {
	if at == nil {
		return v1alpha1.AccessTokenObservation{}
	}

	return v1alpha1.AccessTokenObservation{
		ID:          at.ID,
		Name:        at.Name,
		Description: at.Description,
		UserID:      at.UserID,
		Scopes:      at.Scopes,
		ExpiresAt:   common.TimeToMetaTime((*time.Time)(at.ExpiresAt)),
		Active:      at.Active,
		CreatedAt:   common.TimeToMetaTime(at.CreatedAt),
		Revoked:     at.Revoked,
		AccessLevel: int64(at.AccessLevel),
	}
}

// GenerateRotateProjectAccessTokenOptions generates project access token rotation options
func GenerateRotateProjectAccessTokenOptions(p *v1alpha1.AccessTokenParameters) *gitlab.RotateProjectAccessTokenOptions {
	accesstoken := &gitlab.RotateProjectAccessTokenOptions{}

	if p.ExpiresAt != nil {
		accesstoken.ExpiresAt = (*gitlab.ISOTime)(&p.ExpiresAt.Time)
	} else if p.RenewalPeriodDays != nil {
		accesstoken.ExpiresAt = common.GenerateRenewalExpiration(*p.RenewalPeriodDays)
	}

	return accesstoken
}

// GenerateRotateSelfOptions generates self-rotation options from access token parameters.
func GenerateRotateSelfOptions(p *v1alpha1.AccessTokenParameters) *gitlab.RotatePersonalAccessTokenOptions {
	opt := &gitlab.RotatePersonalAccessTokenOptions{}

	if p.ExpiresAt != nil {
		opt.ExpiresAt = (*gitlab.ISOTime)(&p.ExpiresAt.Time)
	} else if p.RenewalPeriodDays != nil {
		opt.ExpiresAt = common.GenerateRenewalExpiration(*p.RenewalPeriodDays)
	}

	return opt
}

// ShouldRotateAccessToken returns true when the token must be rotated.
func ShouldRotateAccessToken(p *v1alpha1.AccessTokenParameters, a *gitlab.ProjectAccessToken) bool {
	if a == nil {
		return true
	}

	var desiredExpiresAt *time.Time
	if p != nil && p.ExpiresAt != nil {
		desiredExpiresAt = &p.ExpiresAt.Time
	}

	var createdAt *time.Time
	if p != nil && p.RenewalPeriodDays != nil {
		createdAt = a.CreatedAt
	}

	return common.ShouldRotateToken(a.Active, createdAt, a.ExpiresAt, desiredExpiresAt)
}
