/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by hack/generate-cluster-scope.go - DO NOT EDIT.

package projects

import (
	"time"

	gitlab "gitlab.com/gitlab-org/api/client-go/v2"
	"k8s.io/utils/ptr"

	"github.com/crossplane-contrib/provider-gitlab/apis/cluster/projects/v1alpha1"
	"github.com/crossplane-contrib/provider-gitlab/pkg/common"
)

// ServiceAccountAccessTokenClient defines GitLab project service account personal
// access token operations.
type ServiceAccountAccessTokenClient interface {
	// Owner-authenticated endpoints (the ProviderConfig is a project owner/maintainer).
	ListProjectServiceAccountPersonalAccessTokens(pid any, serviceAccount int64, opt *gitlab.ListProjectServiceAccountPersonalAccessTokensOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.PersonalAccessToken, *gitlab.Response, error)
	CreateProjectServiceAccountPersonalAccessToken(pid any, serviceAccount int64, opt *gitlab.CreateProjectServiceAccountPersonalAccessTokenOptions, options ...gitlab.RequestOptionFunc) (*gitlab.PersonalAccessToken, *gitlab.Response, error)
	RevokeProjectServiceAccountPersonalAccessToken(pid any, serviceAccount, token int64, options ...gitlab.RequestOptionFunc) (*gitlab.Response, error)
	RotateProjectServiceAccountPersonalAccessToken(pid any, serviceAccount, token int64, opt *gitlab.RotateProjectServiceAccountPersonalAccessTokenOptions, options ...gitlab.RequestOptionFunc) (*gitlab.PersonalAccessToken, *gitlab.Response, error)

	// Self-authenticated endpoints (the ProviderConfig authenticates with the
	// very token this resource manages). Used in self-managed mode.
	GetServiceAccountSelf(options ...gitlab.RequestOptionFunc) (*gitlab.PersonalAccessToken, *gitlab.Response, error)
	RotateServiceAccountSelf(opt *gitlab.RotatePersonalAccessTokenOptions, options ...gitlab.RequestOptionFunc) (*gitlab.PersonalAccessToken, *gitlab.Response, error)
	RevokeServiceAccountSelf(options ...gitlab.RequestOptionFunc) (*gitlab.Response, error)
}

// NewServiceAccountAccessTokenClient returns a new GitLab project service account access token service.
func NewServiceAccountAccessTokenClient(cfg common.Config) ServiceAccountAccessTokenClient {
	git := common.NewClient(cfg)
	return &serviceAccountAccessTokenClient{
		ProjectsServiceInterface:             git.Projects,
		PersonalAccessTokensServiceInterface: git.PersonalAccessTokens,
	}
}

// serviceAccountAccessTokenClient composes project and personal access token services.
type serviceAccountAccessTokenClient struct {
	gitlab.ProjectsServiceInterface
	gitlab.PersonalAccessTokensServiceInterface
}

// GetServiceAccountSelf returns the token used to authenticate the request
// (self-inform), via GET /personal_access_tokens/self.
func (c *serviceAccountAccessTokenClient) GetServiceAccountSelf(options ...gitlab.RequestOptionFunc) (*gitlab.PersonalAccessToken, *gitlab.Response, error) {
	return c.PersonalAccessTokensServiceInterface.GetSinglePersonalAccessToken(options...)
}

// RotateServiceAccountSelf rotates the token used to authenticate the request,
// via POST /personal_access_tokens/self/rotate.
func (c *serviceAccountAccessTokenClient) RotateServiceAccountSelf(opt *gitlab.RotatePersonalAccessTokenOptions, options ...gitlab.RequestOptionFunc) (*gitlab.PersonalAccessToken, *gitlab.Response, error) {
	return c.PersonalAccessTokensServiceInterface.RotatePersonalAccessTokenSelf(opt, options...)
}

// RevokeServiceAccountSelf revokes the token used to authenticate the request,
// via DELETE /personal_access_tokens/self.
func (c *serviceAccountAccessTokenClient) RevokeServiceAccountSelf(options ...gitlab.RequestOptionFunc) (*gitlab.Response, error) {
	return c.PersonalAccessTokensServiceInterface.RevokePersonalAccessTokenSelf(options...)
}

// GetServiceAccountAccessToken paginates over a service account's personal access
// tokens and returns the one matching tokenID. When no token matches it returns
// a nil token and the last response so callers can detect not-found.
func GetServiceAccountAccessToken(c ServiceAccountAccessTokenClient, pid any, serviceAccount, tokenID int64, options ...gitlab.RequestOptionFunc) (*gitlab.PersonalAccessToken, *gitlab.Response, error) {
	opt := &gitlab.ListProjectServiceAccountPersonalAccessTokensOptions{
		ListOptions: gitlab.ListOptions{PerPage: 100, Page: 1},
		// Only active tokens are relevant. A revoked or expired token already
		// surfaces as "not found" (nil result), which the controller treats as
		// ResourceExists: false. Filtering server-side avoids paginating through
		// revoked/expired tokens on every Observe poll, reducing latency and API
		// rate-limit pressure for service accounts with many tokens.
		State: gitlab.Ptr("active"),
	}

	var lastRes *gitlab.Response
	for {
		tokens, res, err := c.ListProjectServiceAccountPersonalAccessTokens(pid, serviceAccount, opt, options...)
		if err != nil {
			return nil, res, err
		}
		lastRes = res

		for _, t := range tokens {
			if t.ID == tokenID {
				return t, res, nil
			}
		}

		if res == nil || res.NextPage == 0 {
			break
		}
		opt.Page = res.NextPage
	}

	return nil, lastRes, nil
}

// GenerateCreateServiceAccountAccessTokenOptions generates creation options.
func GenerateCreateServiceAccountAccessTokenOptions(p *v1alpha1.ServiceAccountAccessTokenParameters) *gitlab.CreateProjectServiceAccountPersonalAccessTokenOptions {
	accesstoken := &gitlab.CreateProjectServiceAccountPersonalAccessTokenOptions{
		Name:   &p.Name,
		Scopes: &p.Scopes,
	}

	if p.ExpiresAt != nil {
		accesstoken.ExpiresAt = (*gitlab.ISOTime)(&p.ExpiresAt.Time)
	} else if p.RenewalPeriodDays != nil {
		accesstoken.ExpiresAt = common.GenerateRenewalExpiration(*p.RenewalPeriodDays)
	}

	if p.Description != nil {
		accesstoken.Description = ptr.To(*p.Description)
	}

	return accesstoken
}

// GenerateServiceAccountAccessTokenObservation generates an observation from a gitlab.PersonalAccessToken.
func GenerateServiceAccountAccessTokenObservation(at *gitlab.PersonalAccessToken) v1alpha1.ServiceAccountAccessTokenObservation {
	if at == nil {
		return v1alpha1.ServiceAccountAccessTokenObservation{}
	}

	return v1alpha1.ServiceAccountAccessTokenObservation{
		ID:          at.ID,
		Name:        at.Name,
		Description: at.Description,
		UserID:      at.UserID,
		Scopes:      at.Scopes,
		ExpiresAt:   common.TimeToMetaTime((*time.Time)(at.ExpiresAt)),
		Active:      at.Active,
		CreatedAt:   common.TimeToMetaTime(at.CreatedAt),
		LastUsedAt:  common.TimeToMetaTime(at.LastUsedAt),
		Revoked:     at.Revoked,
	}
}

// GenerateRotateServiceAccountAccessTokenOptions generates owner-mode rotation options.
func GenerateRotateServiceAccountAccessTokenOptions(p *v1alpha1.ServiceAccountAccessTokenParameters) *gitlab.RotateProjectServiceAccountPersonalAccessTokenOptions {
	accesstoken := &gitlab.RotateProjectServiceAccountPersonalAccessTokenOptions{}

	if p.ExpiresAt != nil {
		accesstoken.ExpiresAt = (*gitlab.ISOTime)(&p.ExpiresAt.Time)
	} else if p.RenewalPeriodDays != nil {
		accesstoken.ExpiresAt = common.GenerateRenewalExpiration(*p.RenewalPeriodDays)
	}

	return accesstoken
}

// GenerateRotateServiceAccountSelfOptions generates self-rotation options from parameters.
func GenerateRotateServiceAccountSelfOptions(p *v1alpha1.ServiceAccountAccessTokenParameters) *gitlab.RotatePersonalAccessTokenOptions {
	opt := &gitlab.RotatePersonalAccessTokenOptions{}

	if p.ExpiresAt != nil {
		opt.ExpiresAt = (*gitlab.ISOTime)(&p.ExpiresAt.Time)
	} else if p.RenewalPeriodDays != nil {
		opt.ExpiresAt = common.GenerateRenewalExpiration(*p.RenewalPeriodDays)
	}

	return opt
}

// ShouldRotateServiceAccountAccessToken returns true when the token must be rotated.
func ShouldRotateServiceAccountAccessToken(p *v1alpha1.ServiceAccountAccessTokenParameters, a *gitlab.PersonalAccessToken) bool {
	if a == nil {
		return true
	}

	var desiredExpiresAt *time.Time
	if p.ExpiresAt != nil {
		desiredExpiresAt = &p.ExpiresAt.Time
	}

	var createdAt *time.Time
	if p.RenewalPeriodDays != nil {
		createdAt = a.CreatedAt
	}

	return common.ShouldRotateToken(a.Active, createdAt, a.ExpiresAt, desiredExpiresAt, p.RenewBeforeDays, time.Now().UTC())
}
