apiVersion: projects.gitlab.m.crossplane.io/v1alpha1
kind: Member
metadata:
  namespace: example-namespace
spec:
  forProvider:
    accessLevel: 30
    expiresAt: "2024-12-31"
    projectId: 1
    projectIdRef:
      name: string
      namespace: string
      policy:
        resolution: "Required"
        resolve: "Always" # "Always", "IfNotPresent"
    projectIdSelector:
      matchControllerRef: true
      matchLabels: {}
      namespace: string
      policy:
        resolution: "Required"
        resolve: "Always" # "Always", "IfNotPresent"
    userID: 123
    userName: "john.doe"
  managementPolicies: ["*"]
  providerConfigRef:
    kind: string
    name: string
  writeConnectionSecretToRef:
    name: string
