apiVersion: projects.gitlab.m.crossplane.io/v1alpha1
kind: AccessToken
metadata:
  name: example-access-token
  namespace: default
spec:
  forProvider:
    name: example-access-token
    projectIdRef:
      name: example-project
    accessLevel: 40
    expiresAt: "2026-06-15T08:00:00Z"
    scopes:
      - "read_repository"
  providerConfigRef:
    name: gitlab-provider
    kind: ProviderConfig
  writeConnectionSecretToRef:
    name: gitlab-example-access-token
---
apiVersion: projects.gitlab.m.crossplane.io/v1alpha1
kind: AccessToken
metadata:
  name: example-access-token-no-expiry
  namespace: default
spec:
  forProvider:
    name: example-access-token-no-expiry
    projectIdRef:
      name: example-project
    accessLevel: 40
    renewalPeriodDays: 5 # Configure auto renewal every 5 days
    scopes:
      - "read_repository"
  providerConfigRef:
    name: gitlab-provider
    kind: ProviderConfig
  writeConnectionSecretToRef:
    name: gitlab-example-access-token-no-expiry
