apiVersion: projects.gitlab.crossplane.io/v1alpha1
kind: GroupProject
metadata:
  name: example-group-project
spec:
  forProvider:
    namespaceIdRef:
        name: example-group
    description: "example group project description"
  providerConfigRef:
    name: gitlab-provider
  # a reference to a Kubernetes secret to which the controller will write the runnersToken
  writeConnectionSecretToRef:
    name: gitlab-groupproject-example-groupproject
    namespace: crossplane-system
