---
apiVersion: projects.gitlab.m.crossplane.io/v1alpha1
kind: IntegrationHarbor
metadata:
  name: harbor-p7
  namespace: default
spec:
  providerConfigRef:
    name: gitlab-provider
    kind: ProviderConfig
  forProvider:
    projectId: 7
    url: "https://registry.boxboxjason.dev"
    projectName: "library"
    username: "robot$test"
    passwordSecretRef:
      name: harbor-credentials
      key: token
