apiVersion: projects.gitlab.m.crossplane.io/v1alpha1
kind: Project
metadata:
  name: example-project
  namespace: default
spec:
  forProvider:
    # If not set, metadata.name will be used instead.
    name: "Example Project"
    namespaceIdRef:
      name: example-group
    description: "example project description"
    buildGitStrategy: "fetch"
    # Merge request approval configuration for the project. Fields left
    # unset here are not managed by this provider.
    approvals:
      resetApprovalsOnPush: true
      disableOverridingApproversPerMergeRequest: false
      mergeRequestsAuthorApproval: false
      mergeRequestsDisableCommittersApproval: true
      requireReauthenticationToApprove: true
      selectiveCodeOwnerRemovals: false
  providerConfigRef:
    name: gitlab-provider
    kind: ProviderConfig
  # a reference to a Kubernetes secret to which the controller will write the runnersToken
  writeConnectionSecretToRef:
    name: gitlab-project-example-project
