apiVersion: v1
kind: Secret
metadata:
  name: example-repositoryfile-content
  namespace: default
type: Opaque
stringData:
  content: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: generated-file
---
apiVersion: projects.gitlab.crossplane.io/v1alpha1
kind: RepositoryFile
metadata:
  name: example-repositoryfile-secret
spec:
  forProvider:
    projectIdRef:
      name: example-project
    filePath: manifests/generated-file.yaml
    branch: main
    contentSecretRef:
      name: example-repositoryfile-content
      key: content
    reconcileInterval: 2h
    createCommitMessage: "feat: add generated manifest"
    updateCommitMessage: "feat: update generated manifest"
    deleteCommitMessage: "feat: remove generated manifest"
  providerConfigRef:
    name: gitlab-provider
