---
apiVersion: projects.gitlab.m.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  name: example-project-sa
  namespace: default
spec:
  providerConfigRef:
    name: gitlab-provider
    kind: ProviderConfig
  forProvider:
    # The project that owns the service account, by ID or reference.
    projectIdRef:
      name: example-project
    name: Example Project Service Account
    username: example-project-sa
