# Example UserRunner for a GitLab project
# IMPORTANT: The writeConnectionSecretToRef is REQUIRED to receive the runner token.
# Without this, the runner cannot be registered and is unusable.
apiVersion: projects.gitlab.crossplane.io/v1alpha1
kind: UserRunner
metadata:
  name: example-project-runner
spec:
  forProvider:
    projectIdRef:
      name: example-project
    description: "example project runner description"
    tagList:
      - "example-tag-1"
      - "example-tag-2"
  providerConfigRef:
    name: gitlab-provider
  # REQUIRED: This creates a Kubernetes secret containing the runner token
  # The token is needed to register the GitLab Runner agent
  writeConnectionSecretToRef:
    name: gitlab-example-project-runner-token
    namespace: crossplane-system
