# Example Runner for a GitLab instance
# IMPORTANT: The writeConnectionSecretToRef is REQUIRED to receive the runner token.
# Without this, the runner cannot be registered and is unusable.
apiVersion: instance.gitlab.m.crossplane.io/v1alpha1
kind: Runner
metadata:
  namespace: default
  name: example-instance-runner
spec:
  forProvider:
    description: "example instance runner description"
    tagList:
      - "example-tag-1"
      - "example-tag-2"
  providerConfigRef:
    name: gitlab-provider
    kind: ProviderConfig
  # REQUIRED: This creates a Kubernetes secret containing the runner token
  # The token is needed to register the GitLab Runner agent
  writeConnectionSecretToRef:
    name: gitlab-example-instance-runner-token
